CREATE ROLE KN_LOGISTICS_DEVELOPERS;

-- Grant privilege to AcocuntAdmin
GRANT OWNERSHIP ON DATABASE KN_LOGISTICS TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;

GRANT USAGE ON DATABASE KN_LOGISTICS TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA KN_LOGISTICS.SNOWSQL TO ROLE ACCOUNTADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA KN_LOGISTICS.SNOWSQL TO ROLE ACCOUNTADMIN;


GRANT ALL PRIVILEGES 
ON WAREHOUSE KN_LOGISTICS 
TO ROLE KN_LOGISTICS_DEVELOPERS 
WITH GRANT OPTION;

GRANT ROLE KN_LOGISTICS_DEVELOPERS TO USER CATFISH;
GRANT ROLE KN_LOGISTICS_DEVELOPERS TO USER CAT;
GRANT ROLE KN_LOGISTICS_DEVELOPERS TO USER CHEETAH;
GRANT ROLE KN_LOGISTICS_DEVELOPERS TO USER CAMEL;
GRANT ROLE KN_LOGISTICS_DEVELOPERS TO USER CHIPMUNK;


-- Grant access to the database
GRANT USAGE ON DATABASE KN_LOGISTICS TO ROLE KN_LOGISTICS_DEVELOPERS;

-- Grant access to schemas within the database
GRANT USAGE ON ALL SCHEMAS IN DATABASE KN_LOGISTICS TO ROLE KN_LOGISTICS_DEVELOPERS;

-- Grant access to all tables in the database's schemas
GRANT SELECT ON ALL TABLES IN SCHEMA KN_LOGISTICS.SNOWSQL TO ROLE KN_LOGISTICS_DEVELOPERS;

-- Ensure access to future tables in the schema
GRANT SELECT ON FUTURE TABLES IN SCHEMA KN_LOGISTICS.SNOWSQL TO ROLE KN_LOGISTICS_DEVELOPERS;


REVOKE USAGE ON DATABASE KN_LOGISTICS FROM ROLE TRAINING_ROLE;
REVOKE USAGE ON ALL SCHEMAS IN DATABASE KN_LOGISTICS FROM ROLE TRAINING_ROLE;
REVOKE SELECT ON ALL TABLES IN SCHEMA KN_LOGISTICS.SNOWSQL FROM ROLE TRAINING_ROLE;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA KN_LOGISTICS.SNOWSQL FROM ROLE TRAINING_ROLE;

GRANT OWNERSHIP ON DATABASE KN_LOGISTICS TO ROLE KN_LOGISTICS_DEVELOPERS REVOKE CURRENT GRANTS;

SHOW DATABASES LIKE 'KN_LOGISTICS';

SHOW GRANTS TO ROLE KN_LOGISTICS_DEVELOPERS;
