# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.0.1
  github-cli: circleci/github-cli@2.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:

  build_image_and_deploy:
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: "Build docker image and push to Quay"
          command: |
            docker login -u="${QUAY_USER}" -p="${QUAY_PASSWORD}" quay.io
            image_tag=quay.io/astronomer/astro-trial-examples:astro-$(date +%Y%m%d%H%M%S)
            docker build -t ${image_tag} .
            docker push ${image_tag}
            curl -sSL install.astronomer.io | sudo bash -s
            astro deploy -i ${image_tag} ${ASTRO_DEPLOYMENT_ID} -f



# Invoke jobs with workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build_image_and_deploy:
          context:
             - astro-example-dags
          filters:
            branches:
              only:
                - main
