-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS AS
SELECT
  CAST(CASE WHEN PAYMENTMETHODID = 'NULL' THEN NULL ELSE PAYMENTMETHODID END AS VARCHAR(20)) AS PAYMENTMETHODID,
  CAST(CASE WHEN PAYMENTMETHODNAME = 'NULL' THEN NULL ELSE PAYMENTMETHODNAME END AS VARCHAR(50)) AS PAYMENTMETHODNAME
FROM KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES_RAW;

-- Verify the clean table
SELECT *
FROM KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS;

-----------------------------------------------------------------------------------------
// Data type conversion (to number): PAYMENTMETHODID
-----------------------------------------------------------------------------------------
// PAYMENTMETHODID
ALTER TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
ADD COLUMN PAYMENTMETHODID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
SET PAYMENTMETHODID_NUM = TO_NUMBER(PAYMENTMETHODID);

SELECT PAYMENTMETHODID, PAYMENTMETHODID_NUM
FROM KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
DROP COLUMN PAYMENTMETHODID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
RENAME COLUMN PAYMENTMETHODID_NUM TO PAYMENTMETHODID;

// Check 10 rows of PAYMENTMETHODID after updating the data type
SELECT PAYMENTMETHODID FROM KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS LIMIT 10;

// Check 10 rows of the whole table after updating the data type
SELECT * FROM KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS;

---------------------------------------------------------------
--Adding of primary key to table
---------------------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
ADD CONSTRAINT PK_APPLICATION_PAYMENTMETHODS_PAYMENTMETHODID
PRIMARY KEY (PAYMENTMETHODID);

----------------------------------------------------------------
--Adding of unique key to table
----------------------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
ADD CONSTRAINT UK_APPLICATION_PAYMENTMETHODS_PAYMENTMETHODNAME
UNIQUE (PAYMENTMETHODNAME);

-------------------------------------------------------
-- ERROR HANDLING
-------------------------------------------------------
WITH CTE AS (
    SELECT 
        PAYMENTMETHODID,
        PAYMENTMETHODNAME,
        LAG(PAYMENTMETHODID) OVER (ORDER BY PAYMENTMETHODID) AS prev_paymentmethodid,
        ROW_NUMBER() OVER (ORDER BY PAYMENTMETHODID) AS row_num
    FROM KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS
)
SELECT 
    PAYMENTMETHODNAME,
    CASE
        WHEN PAYMENTMETHODID IS NULL THEN prev_paymentmethodid + 1
        ELSE PAYMENTMETHODID
    END AS PAYMENTMETHODID
FROM CTE
ORDER BY row_num;

-------------------------------------------------------
--Adding of foreign key to table
-------------------------------------------------------
-- THERE IS NO FOREIGN KEY IN THIS TABLE
