-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS AS
SELECT
  CAST(CASE WHEN SUPPLIERID = 'NULL' THEN NULL ELSE SUPPLIERID END AS VARCHAR(38)) AS SUPPLIERID,
  CAST(CASE WHEN SUPPLIERNAME = 'NULL' THEN NULL ELSE SUPPLIERNAME END AS VARCHAR(100)) AS SUPPLIERNAME,
  CAST(CASE WHEN SUPPLIERCATEGORYID = 'NULL' THEN NULL ELSE SUPPLIERCATEGORYID END AS VARCHAR(38)) AS SUPPLIERCATEGORYID,
  CAST(CASE WHEN PRIMARYCONTACTPERSONID = 'NULL' THEN NULL ELSE PRIMARYCONTACTPERSONID END AS VARCHAR(38)) AS PRIMARYCONTACTPERSONID,
  CAST(CASE WHEN ALTERNATECONTACTPERSONID = 'NULL' THEN NULL ELSE ALTERNATECONTACTPERSONID END AS VARCHAR(38)) AS ALTERNATECONTACTPERSONID,
  CAST(CASE WHEN DELIVERYMETHODID = 'NULL' THEN NULL ELSE DELIVERYMETHODID END AS VARCHAR(38)) AS DELIVERYMETHODID,
  CAST(CASE WHEN DELIVERYCITYID = 'NULL' THEN NULL ELSE DELIVERYCITYID END AS VARCHAR(38)) AS DELIVERYCITYID,
  CAST(CASE WHEN POSTALCITYID = 'NULL' THEN NULL ELSE POSTALCITYID END AS VARCHAR(38)) AS POSTALCITYID,
  CAST(CASE WHEN SUPPLIERREFERENCE = 'NULL' THEN NULL ELSE SUPPLIERREFERENCE END AS VARCHAR(20)) AS SUPPLIERREFERENCE,
  CAST(CASE WHEN PAYMENTDAYS = 'NULL' THEN NULL ELSE PAYMENTDAYS END AS VARCHAR(38)) AS PAYMENTDAYS,
  CAST(CASE WHEN PHONENUMBER = 'NULL' THEN NULL ELSE PHONENUMBER END AS VARCHAR(20)) AS PHONENUMBER,
  CAST(CASE WHEN WEBSITEURL = 'NULL' THEN NULL ELSE WEBSITEURL END AS VARCHAR(256)) AS WEBSITEURL,
  CAST(CASE WHEN DELIVERYADDRESSLINE = 'NULL' THEN NULL ELSE DELIVERYADDRESSLINE END AS VARCHAR(60)) AS DELIVERYADDRESSLINE,
  CAST(CASE WHEN DELIVERYLOCATIONLAT = 'NULL' THEN NULL ELSE DELIVERYLOCATIONLAT END AS VARCHAR(60)) AS DELIVERYLOCATIONLAT,
  CAST(CASE WHEN DELIVERYLOCATIONLONG = 'NULL' THEN NULL ELSE DELIVERYLOCATIONLONG END AS VARCHAR(60)) AS DELIVERYLOCATIONLONG
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS_RAW;

-- DROPPING 5 COUMNS - DELIVERYCITYID, POSTALCITYID, DELIVERYADDRESSLINE, DELIVERYLOCATIONLAT
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN DELIVERYCITYID, POSTALCITYID, DELIVERYADDRESSLINE, DELIVERYLOCATIONLAT, DELIVERYLOCATIONLONG;

---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN SUPPLIERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET SUPPLIERID_NUM = TO_NUMBER(SUPPLIERID);

SELECT SUPPLIERID, SUPPLIERID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN SUPPLIERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN SUPPLIERID_NUM TO SUPPLIERID;


---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN DELIVERYMETHODID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET DELIVERYMETHODID_NUM = TO_NUMBER(DELIVERYMETHODID);

SELECT DELIVERYMETHODID, DELIVERYMETHODID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN DELIVERYMETHODID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN DELIVERYMETHODID_NUM TO DELIVERYMETHODID;

--------------------------------------------------
-- data type conversion (to number) SUPPLIERCATEGORYID 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN SUPPLIERCATEGORYID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET SUPPLIERCATEGORYID_NUM = TO_NUMBER(SUPPLIERCATEGORYID);

SELECT SUPPLIERCATEGORYID, SUPPLIERCATEGORYID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN SUPPLIERCATEGORYID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN SUPPLIERCATEGORYID_NUM TO SUPPLIERCATEGORYID;

--------------------------------------------------
-- data type conversion (to number) PAYMENTDAYS 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN PAYMENTDAYS_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET PAYMENTDAYS_NUM = TO_NUMBER(PAYMENTDAYS);

SELECT PAYMENTDAYS, PAYMENTDAYS_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN PAYMENTDAYS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN PAYMENTDAYS_NUM TO PAYMENTDAYS;

--------------------------------------------------
-- data type conversion (to number) PRIMARYCONTACTPERSONID 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN PRIMARYCONTACTPERSONID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET PRIMARYCONTACTPERSONID_NUM = TO_NUMBER(PRIMARYCONTACTPERSONID);

SELECT PRIMARYCONTACTPERSONID, PRIMARYCONTACTPERSONID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN PRIMARYCONTACTPERSONID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN PRIMARYCONTACTPERSONID_NUM TO PRIMARYCONTACTPERSONID;


--------------------------------------------------
-- data type conversion (to number) ALTERNATECONTACTPERSONID 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN ALTERNATECONTACTPERSONID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET ALTERNATECONTACTPERSONID_NUM = TO_NUMBER(ALTERNATECONTACTPERSONID);

SELECT ALTERNATECONTACTPERSONID, ALTERNATECONTACTPERSONID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN ALTERNATECONTACTPERSONID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN ALTERNATECONTACTPERSONID_NUM TO ALTERNATECONTACTPERSONID;

-- Check 10 rows of SUPPLIERID after updating the data type
SELECT ALTERNATECONTACTPERSONID FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS LIMIT 10;


-- primary keys
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD CONSTRAINT PK_PURCHASING_SUPPLIERS_SUPPLIERID
PRIMARY KEY (SUPPLIERID);

-- unique keys
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD CONSTRAINT UK_PURCHASING_SUPPLIERS_SUPPLIERNAME
UNIQUE (SUPPLIERNAME);


-- null error handling for primary key (increment 1 to impute null value primary keys from the previous record)
WITH CTE AS (
    SELECT
        SUPPLIERID, 
        SUPPLIERNAME,
        SUPPLIERREFERENCE,
        PHONENUMBER,
        WEBSITEURL,
        DELIVERYMETHODID,
        SUPPLIERCATEGORYID,
        PAYMENTDAYS,
        PRIMARYCONTACTPERSONID,
        ALTERNATECONTACTPERSONID,
        LAG(SUPPLIERID) OVER (ORDER BY SUPPLIERID) AS prev_SUPPLIERID,
        ROW_NUMBER() OVER (ORDER BY SUPPLIERID) AS row_num
    FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
)
SELECT 
        SUPPLIERNAME,
        SUPPLIERREFERENCE,
        PHONENUMBER,
        WEBSITEURL,
        DELIVERYMETHODID,
        SUPPLIERCATEGORYID,
        PAYMENTDAYS,
        PRIMARYCONTACTPERSONID,
        ALTERNATECONTACTPERSONID,
    CASE
        WHEN SUPPLIERID IS NULL THEN prev_SUPPLIERID + 1
        ELSE SUPPLIERID
    END AS SUPPLIERID
FROM CTE
ORDER BY row_num;


-- Foreign Key Constraints for Purchasing.Suppliers
ALTER TABLE KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers
ADD CONSTRAINT FK_Purchasing_Suppliers_DeliveryMethodID_Application_DeliveryMethods
FOREIGN KEY (DeliveryMethodID)
REFERENCES KN_LOGISTICS.SNOWSQL.Application_DeliveryMethods(DeliveryMethodID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers
ADD CONSTRAINT FK_Purchasing_Suppliers_AlternateContactPersonID_Application_People
FOREIGN KEY (AlternateContactPersonID)
REFERENCES KN_LOGISTICS.SNOWSQL.Application_People(PersonID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers
ADD CONSTRAINT FK_Purchasing_Suppliers_PrimaryContactPersonID_Application_People
FOREIGN KEY (PrimaryContactPersonID)
REFERENCES KN_LOGISTICS.SNOWSQL.Application_People(PersonID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers
ADD CONSTRAINT FK_Purchasing_Suppliers_SupplierCategoryID_Purchasing_SupplierCategories
FOREIGN KEY (SupplierCategoryID)
REFERENCES KN_LOGISTICS.SNOWSQL.Purchasing_SupplierCategories(SupplierCategoryID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Warehouse_StockItems
ADD CONSTRAINT FK_Warehouse_StockItems_SupplierID_Purchasing_Suppliers
FOREIGN KEY (SupplierID)
REFERENCES KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers(SupplierID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Purchasing_SupplierTransactions
ADD CONSTRAINT FK_Purchasing_SupplierTransactions_SupplierID_Purchasing_Suppliers
FOREIGN KEY (SupplierID)
REFERENCES KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers(SupplierID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Purchasing_PurchaseOrders
ADD CONSTRAINT FK_Purchasing_PurchaseOrders_SupplierID_Purchasing_Suppliers
FOREIGN KEY (SupplierID)
REFERENCES KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers(SupplierID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.Warehouse_StockItemTransactions
ADD CONSTRAINT FK_Warehouse_StockItemTransactions_SupplierID_Purchasing_Suppliers
FOREIGN KEY (SupplierID)
REFERENCES KN_LOGISTICS.SNOWSQL.Purchasing_Suppliers(SupplierID);
