-- Create a clean table with the same structure as the raw table but we pull data from the raw table into this table (final table)
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS AS
SELECT
  CAST(CASE WHEN SUPPLIERTRANSACTIONID = 'NULL' THEN NULL ELSE SUPPLIERTRANSACTIONID END AS VARCHAR(38)) AS SUPPLIERTRANSACTIONID,
  CAST(CASE WHEN SUPPLIERID = 'NULL' THEN NULL ELSE SUPPLIERID END AS VARCHAR(38)) AS SUPPLIERID,
  CAST(CASE WHEN TRANSACTIONTYPEID = 'NULL' THEN NULL ELSE TRANSACTIONTYPEID END AS VARCHAR(38)) AS TRANSACTIONTYPEID,
  CAST(CASE WHEN PURCHASEORDERID = 'NULL' THEN NULL ELSE PURCHASEORDERID END AS VARCHAR(38)) AS PURCHASEORDERID,
  CAST(CASE WHEN PAYMENTMETHODID = 'NULL' THEN NULL ELSE PAYMENTMETHODID END AS VARCHAR(38)) AS PAYMENTMETHODID,
  CAST(CASE WHEN SUPPLIERINVOICENUMBER = 'NULL' THEN NULL ELSE SUPPLIERINVOICENUMBER END AS VARCHAR(20)) AS SUPPLIERINVOICENUMBER,
  CAST(CASE WHEN TRANSACTIONDATE = 'NULL' THEN NULL ELSE TRANSACTIONDATE END AS VARCHAR(20)) AS TRANSACTIONDATE,
  CAST(CASE WHEN AMOUNTEXCLUDINGTAX = 'NULL' THEN NULL ELSE AMOUNTEXCLUDINGTAX END AS VARCHAR(38)) AS AMOUNTEXCLUDINGTAX,
  CAST(CASE WHEN TAXAMOUNT = 'NULL' THEN NULL ELSE TAXAMOUNT END AS VARCHAR(38)) AS TAXAMOUNT,
  CAST(CASE WHEN TRANSACTIONAMOUNT = 'NULL' THEN NULL ELSE TRANSACTIONAMOUNT END AS VARCHAR(38)) AS TRANSACTIONAMOUNT,
  CAST(CASE WHEN OUTSTANDINGBALANCE = 'NULL' THEN NULL ELSE OUTSTANDINGBALANCE END AS VARCHAR(38)) AS OUTSTANDINGBALANCE,
  CAST(CASE WHEN FINALIZATIONDATE = 'NULL' THEN NULL ELSE FINALIZATIONDATE END AS VARCHAR(20)) AS FINALIZATIONDATE,
  CAST(CASE WHEN ISFINALIZED = 'NULL' THEN NULL ELSE ISFINALIZED END AS VARCHAR(38)) AS ISFINALIZED
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS_RAW;

-- check for 'null' for VARCHAR DATA TYPE COLUMNS ONLY
SELECT
    SUM(CASE WHEN SUPPLIERID IS NULL THEN 1 END) AS NULL_COUNT_SUPPLIERID,
    SUM(CASE WHEN PURCHASEORDERID IS NULL THEN 1 END) AS NULL_COUNT_PURCHASEORDERID,
    SUM(CASE WHEN PAYMENTMETHODID IS NULL THEN 1 END) AS NULL_COUNT_PAYMENTMETHODID,
    SUM(CASE WHEN SUPPLIERINVOICENUMBER IS NULL THEN 1 END) AS NULL_COUNT_SUPPLIERINVOICENUMBER,
    SUM(CASE WHEN TRANSACTIONDATE IS NULL THEN 1 END) AS NULL_COUNT_TRANSACTIONDATE,
    SUM(CASE WHEN FINALIZATIONDATE IS NULL THEN 1 END) AS NULL_COUNT_FINALIZATIONDATE,
FROM 
    KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

--  check for actual null values
SELECT 
    COUNT(CASE WHEN SUPPLIERTRANSACTIONID IS NULL THEN 1 END) AS count_SUPPLIERTRANSACTIONID_NULL,
    COUNT(CASE WHEN SUPPLIERID IS NULL THEN 1 END) AS count_SUPPLIERID_NULL,
    COUNT(CASE WHEN TRANSACTIONTYPEID IS NULL THEN 1 END) AS count_TRANSACTIONTYPEID_NULL,
    COUNT(CASE WHEN PURCHASEORDERID IS NULL THEN 1 END) AS count_PURCHASEORDERID_NULL,
    COUNT(CASE WHEN PAYMENTMETHODID IS NULL THEN 1 END) AS count_PAYMENTMETHODID_NULL,
    COUNT(CASE WHEN SUPPLIERINVOICENUMBER IS NULL THEN 1 END) AS count_SUPPLIERINVOICENUMBER_NULL,
    COUNT(CASE WHEN TRANSACTIONDATE IS NULL THEN 1 END) AS count_TRANSACTIONDATE_NULL,
    COUNT(CASE WHEN AMOUNTEXCLUDINGTAX IS NULL THEN 1 END) AS count_AMOUNTEXCLUDINGTAX_NULL,
    COUNT(CASE WHEN TAXAMOUNT IS NULL THEN 1 END) AS count_TAXAMOUNT_NULL,
    COUNT(CASE WHEN TRANSACTIONAMOUNT IS NULL THEN 1 END) AS count_TRANSACTIONAMOUNT_NULL,
    COUNT(CASE WHEN OUTSTANDINGBALANCE IS NULL THEN 1 END) AS count_OUTSTANDINGBALANCE_NULL,
    COUNT(CASE WHEN FINALIZATIONDATE IS NULL THEN 1 END) AS count_FINALIZATIONDATE_NULL,
    COUNT(CASE WHEN ISFINALIZED IS NULL THEN 1 END) AS count_ISFINALIZED_NULL
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN SUPPLIERTRANSACTIONID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET SUPPLIERTRANSACTIONID_NUM = TO_NUMBER(PURCHASEORDERID);

SELECT SUPPLIERTRANSACTIONID, SUPPLIERTRANSACTIONID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN SUPPLIERTRANSACTIONID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN SUPPLIERTRANSACTIONID_NUM TO SUPPLIERTRANSACTIONID;

---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN TRANSACTIONTYPEID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET TRANSACTIONTYPEID_NUM = TO_NUMBER(TRANSACTIONTYPEID);

SELECT TRANSACTIONTYPEID, TRANSACTIONTYPEID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN TRANSACTIONTYPEID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN TRANSACTIONTYPEID_NUM TO TRANSACTIONTYPEID;

---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN PAYMENTMETHODID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET PAYMENTMETHODID_NUM = TO_NUMBER(PAYMENTMETHODID);

SELECT PAYMENTMETHODID, PAYMENTMETHODID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN PAYMENTMETHODID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN PAYMENTMETHODID_NUM TO PAYMENTMETHODID;


---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN PURCHASEORDERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET PURCHASEORDERID_NUM = TO_NUMBER(PURCHASEORDERID);

SELECT PURCHASEORDERID, PURCHASEORDERID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN PURCHASEORDERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN PURCHASEORDERID_NUM TO PURCHASEORDERID;

---------------------------------------------
-- data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN SUPPLIERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET SUPPLIERID_NUM = TO_NUMBER(SUPPLIERID);

SELECT SUPPLIERID, SUPPLIERID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN SUPPLIERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN SUPPLIERID_NUM TO SUPPLIERID;

--------------------------------------------------
-- data type conversion (to float) AMOUNTEXCLUDINGTAX 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN AMOUNTEXCLUDINGTAX_NUM DECIMAL(18, 2);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET AMOUNTEXCLUDINGTAX_NUM = TO_DECIMAL(AMOUNTEXCLUDINGTAX, 18, 2);

SELECT AMOUNTEXCLUDINGTAX, AMOUNTEXCLUDINGTAX_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN AMOUNTEXCLUDINGTAX;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN AMOUNTEXCLUDINGTAX_NUM TO AMOUNTEXCLUDINGTAX;

--------------------------------------------------
-- data type conversion (to float) TAXAMOUNT 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN TAXAMOUNT_NUM DECIMAL(18, 2);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET TAXAMOUNT_NUM = TO_DECIMAL(TAXAMOUNT, 18, 2);

SELECT TAXAMOUNT, TAXAMOUNT_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN TAXAMOUNT;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN TAXAMOUNT_NUM TO TAXAMOUNT;

--------------------------------------------------
-- data type conversion (to float) TRANSACTIONAMOUNT 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN TRANSACTIONAMOUNT_NUM DECIMAL(18, 2);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET TRANSACTIONAMOUNT_NUM = TO_DECIMAL(TRANSACTIONAMOUNT, 18, 2);

SELECT TRANSACTIONAMOUNT, TRANSACTIONAMOUNT_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN TRANSACTIONAMOUNT;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN TRANSACTIONAMOUNT_NUM TO TRANSACTIONAMOUNT;

--------------------------------------------------
-- data type conversion (to float) OUTSTANDINGBALANCE 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN OUTSTANDINGBALANCE_NUM DECIMAL(18, 2);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET OUTSTANDINGBALANCE_NUM = TO_DECIMAL(OUTSTANDINGBALANCE, 18, 2);

SELECT OUTSTANDINGBALANCE, OUTSTANDINGBALANCE_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN OUTSTANDINGBALANCE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN OUTSTANDINGBALANCE_NUM TO OUTSTANDINGBALANCE;

--------------------------------------------------
-- data type conversion (to date) FINALIZATIONDATE 
--------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN FINALIZATIONDATE_DATE DATE;

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET FINALIZATIONDATE_DATE = TO_DATE(FINALIZATIONDATE, 'DD/MM/YYYY');

SELECT FINALIZATIONDATE, FINALIZATIONDATE_DATE
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN FINALIZATIONDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN FINALIZATIONDATE_DATE TO FINALIZATIONDATE;


--------------------------------------------------
-- data type conversion (to date) TRANSACTIONDATE
--------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN TRANSACTIONDATE_DATE DATE;

-- Change to date format for ORDERDATE column
UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET TRANSACTIONDATE_DATE = TO_DATE(TRANSACTIONDATE, 'DD/MM/YYYY');

SELECT TRANSACTIONDATE, TRANSACTIONDATE_DATE
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN TRANSACTIONDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN TRANSACTIONDATE_DATE TO TRANSACTIONDATE;

--------------------------------------------------
--- data type conversion (to float) ISFINALIZED 
--------------------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN ISFINALIZED_NUM BOOLEAN;

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET ISFINALIZED_NUM = TO_BOOLEAN(ISFINALIZED);

SELECT ISFINALIZED, ISFINALIZED_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN ISFINALIZED;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN ISFINALIZED_NUM TO ISFINALIZED;

-- primary key
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT PK_PURCHASING_SUPPLIERTRANSACTIONS_SUPPLIERTRANSACTIONID
PRIMARY KEY (SUPPLIERTRANSACTIONID);

-- null error handling for primary key (increment 1 to impute null value primary keys from the previous record)
WITH CTE AS (
    SELECT
        SUPPLIERID,
        SUPPLIERINVOICENUMBER,
        PURCHASEORDERID,
        AMOUNTEXCLUDINGTAX,
        TAXAMOUNT,
        TRANSACTIONAMOUNT,
        OUTSTANDINGBALANCE,
        FINALIZATIONDATE,
        TRANSACTIONDATE,
        ISFINALIZED,
        SUPPLIERTRANSACTIONID,
        TRANSACTIONTYPEID,
        PAYMENTMETHODID,
        LAG(SUPPLIERTRANSACTIONID) OVER (ORDER BY SUPPLIERTRANSACTIONID) AS prev_SUPPLIERTRANSACTIONID,
        ROW_NUMBER() OVER (ORDER BY SUPPLIERTRANSACTIONID) AS row_num
    FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
)
SELECT 
    SUPPLIERINVOICENUMBER,
    PURCHASEORDERID,
    SUPPLIERID,
    AMOUNTEXCLUDINGTAX,
    TAXAMOUNT,
    TRANSACTIONAMOUNT,
    OUTSTANDINGBALANCE,
    FINALIZATIONDATE,
    TRANSACTIONDATE,
    ISFINALIZED,
    TRANSACTIONTYPEID,
    PAYMENTMETHODID,
    CASE
        WHEN SUPPLIERTRANSACTIONID IS NULL THEN prev_SUPPLIERTRANSACTIONID + 1
        ELSE SUPPLIERTRANSACTIONID
    END AS SUPPLIERTRANSACTIONID
FROM CTE
ORDER BY row_num;

-- Add the foreign key constraint for SUPPLIERID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_SUPPLIERID 
FOREIGN KEY (SUPPLIERID) 
REFERENCES KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS(SUPPLIERID);

-- Add the foreign key constraint for TRANSACTIONTYPEID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_TRANSACTIONTYPEID 
FOREIGN KEY (TRANSACTIONTYPEID) 
REFERENCES KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES(TRANSACTIONTYPEID);

-- Add the foreign key constraint for PURCHASEORDERID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_PURCHASEORDERID 
FOREIGN KEY (PURCHASEORDERID) 
REFERENCES KN_LOGISTICS.SNOWSQL.PURCHASING_PURCHASEORDERS(PURCHASEORDERID);

-- Add the foreign key constraint for PAYMENTMETHODID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_PAYMENTMETHODID 
FOREIGN KEY (PAYMENTMETHODID) 
REFERENCES KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS(PAYMENTMETHODID);
