
-- Step 1: Null String Value "NULL" Checks for All Columns
SELECT
    SUM(CASE WHEN CUSTOMERID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_CUSTOMERID,
    SUM(CASE WHEN CUSTOMERNAME = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_CUSTOMERNAME,
    SUM(CASE WHEN BILLTOCUSTOMERID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_BILLTOCUSTOMERID,
    SUM(CASE WHEN CUSTOMERCATEGORYID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_CUSTOMERCATEGORYID,
    SUM(CASE WHEN BUYINGGROUPID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_BUYINGGROUPID,
    SUM(CASE WHEN PRIMARYCONTACTPERSONID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PRIMARYCONTACTPERSONID,
    SUM(CASE WHEN ALTERNATECONTACTPERSONID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_ALTERNATECONTACTPERSONID,
    SUM(CASE WHEN DELIVERYMETHODID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_DELIVERYMETHODID,
    SUM(CASE WHEN DELIVERYCITYID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_DELIVERYCITYID,
    SUM(CASE WHEN CREDITLIMIT = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_CREDITLIMIT,
    SUM(CASE WHEN ACCOUNTOPENEDDATE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_ACCOUNTOPENEDDATE,
    SUM(CASE WHEN STANDARDDISCOUNTPERCENTAGE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_STANDARDDISCOUNTPERCENTAGE,
    SUM(CASE WHEN ISSTATEMENTSENT = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_ISSTATEMENTSENT,
    SUM(CASE WHEN ISONCREDITHOLD = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_ISONCREDITHOLD,
    SUM(CASE WHEN PAYMENTDAYS = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PAYMENTDAYS,
    SUM(CASE WHEN PHONENUMBER = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PHONENUMBER,
    SUM(CASE WHEN WEBSITEURL = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_WEBSITEURL
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW;

-- Step 2: Null Value Checks for Actual NULL Values
SELECT 
    COUNT(CASE WHEN CUSTOMERID IS NULL THEN 1 END) AS count_CUSTOMERID_NULL,
    COUNT(CASE WHEN CUSTOMERNAME IS NULL THEN 1 END) AS count_CUSTOMERNAME_NULL,
    COUNT(CASE WHEN BILLTOCUSTOMERID IS NULL THEN 1 END) AS count_BILLTOCUSTOMERID_NULL,
    COUNT(CASE WHEN CUSTOMERCATEGORYID IS NULL THEN 1 END) AS count_CUSTOMERCATEGORYID_NULL,
    COUNT(CASE WHEN BUYINGGROUPID IS NULL THEN 1 END) AS count_BUYINGGROUPID_NULL,
    COUNT(CASE WHEN PRIMARYCONTACTPERSONID IS NULL THEN 1 END) AS count_PRIMARYCONTACTPERSONID_NULL,
    COUNT(CASE WHEN ALTERNATECONTACTPERSONID IS NULL THEN 1 END) AS count_ALTERNATECONTACTPERSONID_NULL,
    COUNT(CASE WHEN DELIVERYMETHODID IS NULL THEN 1 END) AS count_DELIVERYMETHODID_NULL,
    COUNT(CASE WHEN DELIVERYCITYID IS NULL THEN 1 END) AS count_DELIVERYCITYID_NULL,
    COUNT(CASE WHEN CREDITLIMIT IS NULL THEN 1 END) AS count_CREDITLIMIT_NULL,
    COUNT(CASE WHEN ACCOUNTOPENEDDATE IS NULL THEN 1 END) AS count_ACCOUNTOPENEDDATE_NULL,
    COUNT(CASE WHEN STANDARDDISCOUNTPERCENTAGE IS NULL THEN 1 END) AS count_STANDARDDISCOUNTPERCENTAGE_NULL,
    COUNT(CASE WHEN ISSTATEMENTSENT IS NULL THEN 1 END) AS count_ISSTATEMENTSENT_NULL,
    COUNT(CASE WHEN ISONCREDITHOLD IS NULL THEN 1 END) AS count_ISONCREDITHOLD_NULL,
    COUNT(CASE WHEN PAYMENTDAYS IS NULL THEN 1 END) AS count_PAYMENTDAYS_NULL,
    COUNT(CASE WHEN PHONENUMBER IS NULL THEN 1 END) AS count_PHONENUMBER_NULL,
    COUNT(CASE WHEN WEBSITEURL IS NULL THEN 1 END) AS count_WEBSITEURL_NULL
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW;


-- Step 4: Check for Duplicates
SELECT CUSTOMERID, COUNT(*) AS count
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
GROUP BY CUSTOMERID
HAVING COUNT(*) > 1;

-- Convert "NULL" String Values into Actual NULL Values
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET CUSTOMERID = NULL
WHERE CUSTOMERID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET CUSTOMERNAME = NULL
WHERE CUSTOMERNAME = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET BILLTOCUSTOMERID = NULL
WHERE BILLTOCUSTOMERID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET CUSTOMERCATEGORYID = NULL
WHERE CUSTOMERCATEGORYID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET BUYINGGROUPID = NULL
WHERE BUYINGGROUPID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET PRIMARYCONTACTPERSONID = NULL
WHERE PRIMARYCONTACTPERSONID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ALTERNATECONTACTPERSONID = NULL
WHERE ALTERNATECONTACTPERSONID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET DELIVERYMETHODID = NULL
WHERE DELIVERYMETHODID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET DELIVERYCITYID = NULL
WHERE DELIVERYCITYID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET CREDITLIMIT = NULL
WHERE CREDITLIMIT = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ACCOUNTOPENEDDATE = NULL
WHERE ACCOUNTOPENEDDATE = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET STANDARDDISCOUNTPERCENTAGE = NULL
WHERE STANDARDDISCOUNTPERCENTAGE = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ISSTATEMENTSENT = NULL
WHERE ISSTATEMENTSENT = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ISONCREDITHOLD = NULL
WHERE ISONCREDITHOLD = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET PAYMENTDAYS = NULL
WHERE PAYMENTDAYS = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET PHONENUMBER = NULL
WHERE PHONENUMBER = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET WEBSITEURL = NULL
WHERE WEBSITEURL = 'NULL';


 -- Step 1a: Change CUSTOMERID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN CUSTOMERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET CUSTOMERID_NUM = TO_NUMBER(CUSTOMERID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN CUSTOMERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN CUSTOMERID_NUM TO CUSTOMERID;

-- Step 2: Change BILLTOCUSTOMERID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN BILLTOCUSTOMERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET BILLTOCUSTOMERID_NUM = TO_NUMBER(BILLTOCUSTOMERID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN BILLTOCUSTOMERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN BILLTOCUSTOMERID_NUM TO BILLTOCUSTOMERID;

-- Step 3: Change CUSTOMERCATEGORYID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN CUSTOMERCATEGORYID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET CUSTOMERCATEGORYID_NUM = TO_NUMBER(CUSTOMERCATEGORYID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN CUSTOMERCATEGORYID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN CUSTOMERCATEGORYID_NUM TO CUSTOMERCATEGORYID;

-- Step 4: Change BUYINGGROUPID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN BUYINGGROUPID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET BUYINGGROUPID_NUM = TO_NUMBER(BUYINGGROUPID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN BUYINGGROUPID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN BUYINGGROUPID_NUM TO BUYINGGROUPID;

-- Step 5: Change PRIMARYCONTACTPERSONID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN PRIMARYCONTACTPERSONID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET PRIMARYCONTACTPERSONID_NUM = TO_NUMBER(PRIMARYCONTACTPERSONID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN PRIMARYCONTACTPERSONID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN PRIMARYCONTACTPERSONID_NUM TO PRIMARYCONTACTPERSONID;

-- Step 6: Change ALTERNATECONTACTPERSONID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN ALTERNATECONTACTPERSONID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ALTERNATECONTACTPERSONID_NUM = TO_NUMBER(ALTERNATECONTACTPERSONID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN ALTERNATECONTACTPERSONID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN ALTERNATECONTACTPERSONID_NUM TO ALTERNATECONTACTPERSONID;

-- Step 7: Change DELIVERYCITYID to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN DELIVERYCITYID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET DELIVERYCITYID_NUM = TO_NUMBER(DELIVERYCITYID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN DELIVERYCITYID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN DELIVERYCITYID_NUM TO DELIVERYCITYID;

-- Step 8: Change ACCOUNTOPENEDDATE to DATE
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN ACCOUNTOPENEDDATE_DATE DATE;

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ACCOUNTOPENEDDATE_DATE = TO_DATE(ACCOUNTOPENEDDATE, 'YYYY-MM-DD');

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN ACCOUNTOPENEDDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN ACCOUNTOPENEDDATE_DATE TO ACCOUNTOPENEDDATE;

-- Step 9: Change STANDARDDISCOUNTPERCENTAGE to FLOAT
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN STANDARDDISCOUNTPERCENTAGE_FLOAT FLOAT;

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET STANDARDDISCOUNTPERCENTAGE_FLOAT = CAST(STANDARDDISCOUNTPERCENTAGE AS FLOAT);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN STANDARDDISCOUNTPERCENTAGE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN STANDARDDISCOUNTPERCENTAGE_FLOAT TO STANDARDDISCOUNTPERCENTAGE;

-- Step 10: Change ISSTATEMENTSENT and ISONCREDITHOLD to BOOLEAN
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN ISSTATEMENTSENT_BOOL BOOLEAN;

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ISSTATEMENTSENT_BOOL = CASE WHEN ISSTATEMENTSENT = 'TRUE' THEN TRUE ELSE FALSE END;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN ISSTATEMENTSENT;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN ISSTATEMENTSENT_BOOL TO ISSTATEMENTSENT;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN ISONCREDITHOLD_BOOL BOOLEAN;

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET ISONCREDITHOLD_BOOL = CASE WHEN ISONCREDITHOLD = 'TRUE' THEN TRUE ELSE FALSE END;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN ISONCREDITHOLD;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN ISONCREDITHOLD_BOOL TO ISONCREDITHOLD;

-- Step 11: Change PAYMENTDAYS to NUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ADD COLUMN PAYMENTDAYS_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
SET PAYMENTDAYS_NUM = TO_NUMBER(PAYMENTDAYS);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
DROP COLUMN PAYMENTDAYS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
RENAME COLUMN PAYMENTDAYS_NUM TO PAYMENTDAYS;

-- Step 12: Change PHONENUMBER to VARCHAR(20) and WEBSITEURL to VARCHAR(256)
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ALTER COLUMN PHONENUMBER SET DATA TYPE VARCHAR(20);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW
ALTER COLUMN WEBSITEURL SET DATA TYPE VARCHAR(256);


-- Final Step: Validate 10 Rows of the Updated Table
SELECT * 
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW 
LIMIT 10;

