create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLDROOMTEMPERATURES_RAW (
	COLDROOMTEMPERATUREID VARCHAR(38),
	COLDROOMSENSORNUMBER VARCHAR(38),
	RECORDEDWHEN VARCHAR(20),
	TEMPERATURE VARCHAR(38)
);

