create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES (
	PACKAGETYPEID VARCHAR,
	PACKAGETYPENAME VARCHAR,
	unique (PACKAGETYPENAME),
	primary key (PACKAGETYPEID)
);

-- Null string value "NULL" checks for all columns (only varchar data type columns) 
SELECT
    SUM(CASE WHEN PACKAGETYPEID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PACKAGETYPEID,
    SUM(CASE WHEN PACKAGETYPENAME = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PACKAGETYPENAME,
FROM 
    KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES;


-- count of null valus in WAREHOUSE_PACKAGETYPES
SELECT 
    SUM(CASE WHEN PACKAGETYPEID IS NULL THEN 1 ELSE 0 END) AS PACKAGETYPEID_NULL_COUNT,
    SUM(CASE WHEN PACKAGETYPENAME IS NULL THEN 1 ELSE 0 END) AS PACKAGETYPENAME_NULL_COUNT
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES;

-- count of duplicate valus in WAREHOUSE_PACKAGETYPES
SELECT 
    PACKAGETYPENAME, 
    COUNT(*) AS DUPLICATE_COUNT
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
GROUP BY PACKAGETYPENAME
HAVING COUNT(*) > 1;

--  check for null values in the primary key in WAREHOUSE_PACKAGETYPES
SELECT *
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
WHERE PACKAGETYPEID IS NULL;

-- check for duplicates in unique column in WAREHOUSE_PACKAGETYPES
SELECT PACKAGETYPENAME, COUNT(*)
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
GROUP BY PACKAGETYPENAME
HAVING COUNT(*) > 1;

-- add new columns
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
ADD COLUMN PACKAGETYPEID_NUM NUMBER(38,0);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
ADD COLUMN PACKAGETYPENAME_NEW VARCHAR(16777216);

-- update new columns with converted values
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
SET PACKAGETYPEID_NUM = CAST(PACKAGETYPEID AS NUMBER),
    PACKAGETYPENAME_NEW = PACKAGETYPENAME; -- No change needed for VARCHAR

-- verify data conversion
SELECT 
    PACKAGETYPEID, PACKAGETYPEID_NUM,
    PACKAGETYPENAME, PACKAGETYPENAME_NEW
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES;

-- drop old columns
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
DROP COLUMN PACKAGETYPEID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
DROP COLUMN PACKAGETYPENAME;

-- rename new columns to original names
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
RENAME COLUMN PACKAGETYPEID_NUM TO PACKAGETYPEID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
RENAME COLUMN PACKAGETYPENAME_NEW TO PACKAGETYPENAME;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES
ADD CONSTRAINT PK_WAREHOUSE_PACKAGETYPES_PACKAGETYPEID
PRIMARY KEY (PACKAGETYPEID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES 
MODIFY COLUMN PACKAGETYPEID SET NOT NULL;

