-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS AS
SELECT
  CAST(CASE WHEN COLORID = 'NULL' THEN NULL ELSE COLORID END AS VARCHAR(38)) AS COLORID,
  CAST(CASE WHEN COLORNAME = 'NULL' THEN NULL ELSE COLORNAME END AS VARCHAR(20)) AS COLORNAME
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS_RAW;

-- Verify the clean table
SELECT *
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS;

-----------------------------------------
--Conversion of column datatype 
-----------------------------------------
//COLORID
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
ADD COLUMN COLORID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
SET COLORID_NUM = CAST(COLORID AS NUMBER(38,0));

SELECT COLORID_NUM, COLORID
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
DROP COLUMN COLORID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
RENAME COLUMN COLORID_NUM TO COLORID;

-- Select the transformed data for verification
SELECT 
    COLORID, COLORNAME
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
LIMIT 10;

-----------------------------------
--Adding of primary key to table
-----------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
ADD CONSTRAINT PK_WAREHOUSE_COLORS_COLORID
PRIMARY KEY (COLORID);

----------------------------------------
--Adding of unique key to table
----------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
ADD CONSTRAINT UK_WAREHOUSE_COLORS_COLORNAME
UNIQUE (COLORNAME);

-------------------------------------------------------
-- ERROR HANDLING
-------------------------------------------------------
WITH CTE AS (
    SELECT 
        COLORID,
        COLORNAME,
        LAG(COLORID) OVER (ORDER BY COLORID) AS prev_colorid,
        ROW_NUMBER() OVER (ORDER BY COLORID) AS row_num
    FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS
)
SELECT 
    COLORNAME,
    CASE
        WHEN COLORID IS NULL THEN prev_colorid + 1
        ELSE COLORID
    END AS COLORID
FROM CTE
ORDER BY row_num;


-------------------------------------------------------
--Adding of foreign key to table
-------------------------------------------------------
-- THERE ARE NO FOREIGN KEYS IN THIS TABLE



