create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS (
	STOCKGROUPID VARCHAR,
	STOCKGROUPNAME VARCHAR,
	unique (STOCKGROUPNAME),
	primary key (STOCKGROUPID)
);

-- Null string value "NULL" checks for all columns (only varchar data type columns) 
SELECT
    SUM(CASE WHEN STOCKGROUPID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_STOCKGROUPID,
    SUM(CASE WHEN STOCKGROUPNAME = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_STOCKGROUPNAME,
FROM 
    KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS;


-- count of null values in WAREHOUSE_STOCKGROUPS
SELECT 
    SUM(CASE WHEN STOCKGROUPID IS NULL THEN 1 ELSE 0 END) AS STOCKGROUPID_NULL_COUNT,
    SUM(CASE WHEN STOCKGROUPNAME IS NULL THEN 1 ELSE 0 END) AS STOCKGROUPNAME_NULL_COUNT
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS;

-- count of duplicate values in WAREHOUSE_STOCKGROUPS
SELECT 
    STOCKGROUPID, 
    COUNT(*) AS DUPLICATE_COUNT
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
GROUP BY STOCKGROUPID
HAVING COUNT(*) > 1;

--  check for null values in the primary key in WAREHOUSE_STOCKGROUPS
SELECT *
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
WHERE STOCKGROUPID IS NULL;

-- check for duplicates in unique column in WAREHOUSE_STOCKGROUPS
SELECT STOCKGROUPNAME, COUNT(*)
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
GROUP BY STOCKGROUPNAME
HAVING COUNT(*) > 1;

-- add new columns with correct data types
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
ADD COLUMN STOCKGROUPID_NUM NUMBER(38,0);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
ADD COLUMN STOCKGROUPNAME_NEW VARCHAR(50);

-- update columns with converted values
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
SET STOCKGROUPID_NUM = CAST(STOCKGROUPID AS NUMBER),
    STOCKGROUPNAME_NEW = STOCKGROUPNAME; -- No change needed for VARCHAR

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
SET STOCKGROUPID_NUM = TRY_CAST(STOCKGROUPID AS NUMBER),
    STOCKGROUPNAME_NEW = STOCKGROUPNAME;

-- verify data conversion
SELECT 
    STOCKGROUPID, STOCKGROUPID_NUM,
    STOCKGROUPNAME, STOCKGROUPNAME_NEW
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS;

-- drop old columns
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
DROP COLUMN STOCKGROUPID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
DROP COLUMN STOCKGROUPNAME;

-- rename new columns to original name
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
RENAME COLUMN STOCKGROUPID_NUM TO STOCKGROUPID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
RENAME COLUMN STOCKGROUPNAME_NEW TO STOCKGROUPNAME;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
ADD CONSTRAINT PK_WAREHOUSE_STOCKGROUPS_STOCKGROUPID
PRIMARY KEY (STOCKGROUPID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS 
MODIFY COLUMN STOCKGROUPID SET NOT NULL;

