create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES (
	VEHICLETEMPERATUREID VARCHAR,
	VEHICLEREGISTRATION VARCHAR,
	CHILLERSENSORNUMBER VARCHAR,
	RECORDEDWHEN VARCHAR,
	TEMPERATURE VARCHAR,
	FULLSENSORDATA VARCHAR,
	primary key (VEHICLETEMPERATUREID)
);

-- Null string value "NULL" checks for all columns (only varchar data type columns) 
SELECT
    SUM(CASE WHEN VEHICLETEMPERATUREID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_VEHICLETEMPERATUREID,
    SUM(CASE WHEN VEHICLEREGISTRATION = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_VEHICLEREGISTRATION,
    SUM(CASE WHEN CHILLERSENSORNUMBER IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT_CHILLERSENSORNUMBER,
    SUM(CASE WHEN RECORDEDWHEN = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_RECORDEDWHEN,
    SUM(CASE WHEN TEMPERATURE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_TEMPERATURE,
    SUM(CASE WHEN FULLSENSORDATA IS NULL THEN 1 ELSE 0 END) AS NULL_COUNT_FULLSENSORDATA,
FROM 
    KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES;
    
-- count of null values in WAREHOUSE_VEHICLETEMPERATURES
SELECT 
    SUM(CASE WHEN VEHICLETEMPERATUREID IS NULL THEN 1 ELSE 0 END) AS VEHICLETEMPERATUREID_NULL_COUNT,
    SUM(CASE WHEN VEHICLEREGISTRATION IS NULL THEN 1 ELSE 0 END) AS VEHICLEREGISTRATION_NULL_COUNT,
    SUM(CASE WHEN CHILLERSENSORNUMBER IS NULL THEN 1 ELSE 0 END) AS CHILLERSENSORNUMBER_NULL_COUNT,
    SUM(CASE WHEN RECORDEDWHEN IS NULL THEN 1 ELSE 0 END) AS RECORDEDWHEN_NULL_COUNT,
    SUM(CASE WHEN TEMPERATURE IS NULL THEN 1 ELSE 0 END) AS TEMPERATURE_NULL_COUNT,
    SUM(CASE WHEN FULLSENSORDATA IS NULL THEN 1 ELSE 0 END) AS FULLSENSORDATA_NULL_COUNT
FROM WAREHOUSE_VEHICLETEMPERATURES;

-- convert 'NULL' string valyes into actual null values
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET VEHICLETEMPERATUREID = NULL -- oTHERS
WHERE VEHICLETEMPERATUREID = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET VEHICLEREGISTRATION = NULL -- oTHERS
WHERE VEHICLEREGISTRATION = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET CHILLERSENSORNUMBER = NULL -- oTHERS
WHERE CHILLERSENSORNUMBER = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET RECORDEDWHEN = NULL -- oTHERS
WHERE RECORDEDWHEN = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET TEMPERATURE = NULL -- oTHERS
WHERE TEMPERATURE = 'NULL';

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET FULLSENSORDATA = NULL -- oTHERS
WHERE FULLSENSORDATA = 'NULL';


-- count of duplicate values in WAREHOUSE_VEHICLETEMPERATURES
SELECT 
    VEHICLETEMPERATUREID, 
    VEHICLEREGISTRATION, 
    CHILLERSENSORNUMBER, 
    RECORDEDWHEN, 
    TEMPERATURE, 
    FULLSENSORDATA, 
    COUNT(*) AS DUPLICATE_COUNT
FROM WAREHOUSE_VEHICLETEMPERATURES
GROUP BY 
    VEHICLETEMPERATUREID, 
    VEHICLEREGISTRATION, 
    CHILLERSENSORNUMBER, 
    RECORDEDWHEN, 
    TEMPERATURE, 
    FULLSENSORDATA
HAVING COUNT(*) > 1;

--  check for null values in the primary key in WAREHOUSE_VEHICLETEMPERATURES
SELECT *
FROM WAREHOUSE_VEHICLETEMPERATURES
WHERE VEHICLETEMPERATUREID IS NULL;

-- add new columns with the correct data type
-- Add new column for VEHICLETEMPERATUREID
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
ADD COLUMN VEHICLETEMPERATUREID_NEW NUMBER(38,0) NOT NULL;

-- Add new column for VEHICLEREGISTRATION
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
ADD COLUMN VEHICLEREGISTRATION_NEW VARCHAR(255);

-- Add new column for CHILLERSENSORNUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
ADD COLUMN CHILLERSENSORNUMBER_NEW NUMBER(38,0);

-- Add new column for RECORDEDWHEN
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
ADD COLUMN RECORDEDWHEN_NEW TIMESTAMP_NTZ(9);

-- Add new column for TEMPERATURE
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
ADD COLUMN TEMPERATURE_NEW FLOAT;

-- Add new column for FULLSENSORDATA
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
ADD COLUMN FULLSENSORDATA_NEW STRING;


-- update new columns with converted data'-- Update VEHICLETEMPERATUREID_NEW
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET VEHICLETEMPERATUREID_NEW = TO_NUMBER(VEHICLETEMPERATUREID);

-- Update VEHICLEREGISTRATION_NEW
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET VEHICLEREGISTRATION_NEW = VEHICLEREGISTRATION;

-- Update CHILLERSENSORNUMBER_NEW
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET CHILLERSENSORNUMBER_NEW = TO_NUMBER(CHILLERSENSORNUMBER);

-- Update RECORDEDWHEN_NEW
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET RECORDEDWHEN_NEW = TO_TIMESTAMP(RECORDEDWHEN);

-- Update TEMPERATURE_NEW
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET TEMPERATURE_NEW = TEMPERATURE::FLOAT;


-- Update FULLSENSORDATA_NEW
UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
SET FULLSENSORDATA_NEW = FULLSENSORDATA;


-- drop old columns
-- Drop VEHICLETEMPERATUREID
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
DROP COLUMN VEHICLETEMPERATUREID;

-- Drop VEHICLEREGISTRATION
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
DROP COLUMN VEHICLEREGISTRATION;

-- Drop CHILLERSENSORNUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
DROP COLUMN CHILLERSENSORNUMBER;

-- Drop RECORDEDWHEN
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
DROP COLUMN RECORDEDWHEN;

-- Drop TEMPERATURE
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
DROP COLUMN TEMPERATURE;

-- Drop FULLSENSORDATA
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
DROP COLUMN FULLSENSORDATA;


-- rename new columns
-- Rename VEHICLETEMPERATUREID_NEW to VEHICLETEMPERATUREID
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
RENAME COLUMN VEHICLETEMPERATUREID_NEW TO VEHICLETEMPERATUREID;

-- Rename VEHICLEREGISTRATION_NEW to VEHICLEREGISTRATION
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
RENAME COLUMN VEHICLEREGISTRATION_NEW TO VEHICLEREGISTRATION;

-- Rename CHILLERSENSORNUMBER_NEW to CHILLERSENSORNUMBER
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
RENAME COLUMN CHILLERSENSORNUMBER_NEW TO CHILLERSENSORNUMBER;

-- Rename RECORDEDWHEN_NEW to RECORDEDWHEN
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
RENAME COLUMN RECORDEDWHEN_NEW TO RECORDEDWHEN;

-- Rename TEMPERATURE_NEW to TEMPERATURE
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
RENAME COLUMN TEMPERATURE_NEW TO TEMPERATURE;

-- Rename FULLSENSORDATA_NEW to FULLSENSORDATA
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
RENAME COLUMN FULLSENSORDATA_NEW TO FULLSENSORDATA;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES
ADD CONSTRAINT PK_WAREHOUSE_VEHICLETEMPERATURES_VEHICLETEMPERATUREID
PRIMARY KEY (VEHICLETEMPERATUREID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES 
MODIFY COLUMN VEHICLETEMPERATUREID SET NOT NULL;




