
-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS AS
SELECT
  CAST(CASE WHEN STOCKITEMSTOCKGROUPID = 'NULL' THEN NULL ELSE STOCKITEMSTOCKGROUPID END AS VARCHAR(38)) AS STOCKITEMSTOCKGROUPID,
  CAST(CASE WHEN STOCKITEMID = 'NULL' THEN NULL ELSE STOCKITEMID END AS VARCHAR(38)) AS STOCKITEMID,
  CAST(CASE WHEN STOCKGROUPID = 'NULL' THEN NULL ELSE STOCKGROUPID END AS VARCHAR(38)) AS STOCKGROUPID
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS_RAW;

-- Verify the clean table
SELECT *
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS;

-------------------------------------
--CONVERSION OF DATATYPES
-------------------------------------
---------------------------------------------
-- Data type conversion for StockItemStockGroupID
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD COLUMN STOCKITEMSTOCKGROUPID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
SET STOCKITEMSTOCKGROUPID_NUM = TO_NUMBER(STOCKITEMSTOCKGROUPID);

SELECT STOCKITEMSTOCKGROUPID, STOCKITEMSTOCKGROUPID_NUM
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
DROP COLUMN STOCKITEMSTOCKGROUPID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
RENAME COLUMN STOCKITEMSTOCKGROUPID_NUM TO STOCKITEMSTOCKGROUPID;

---------------------------------------------
-- Data type conversion for StockItemID
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD COLUMN STOCKITEMID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
SET STOCKITEMID_NUM = TO_NUMBER(STOCKITEMID);

SELECT STOCKITEMID, STOCKITEMID_NUM
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
DROP COLUMN STOCKITEMID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
RENAME COLUMN STOCKITEMID_NUM TO STOCKITEMID;

---------------------------------------------
-- Data type conversion for StockGroupID
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD COLUMN STOCKGROUPID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
SET STOCKGROUPID_NUM = TO_NUMBER(STOCKGROUPID);

SELECT STOCKGROUPID, STOCKGROUPID_NUM
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
DROP COLUMN STOCKGROUPID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
RENAME COLUMN STOCKGROUPID_NUM TO STOCKGROUPID;

---------------------------------
-- Add primary key to the table
---------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD CONSTRAINT PK_STOCKITEM_STOCKGROUPS
PRIMARY KEY (STOCKITEMSTOCKGROUPID);

------------------------------------------
--Add unique keys to the table
------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD CONSTRAINT UK_WAREHOUSE_STOCKITEMSTOCKGROUPS_STOCKITEMID
UNIQUE (STOCKITEMID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD CONSTRAINT UK_WAREHOUSE_STOCKITEMSTOCKGROUPS_STOCKGROUPID
UNIQUE (STOCKGROUPID);


-------------------------------------------
-- Error handling for missing values
-------------------------------------------
WITH CTE AS (
    SELECT 
        STOCKITEMSTOCKGROUPID,
        STOCKITEMID,
        STOCKGROUPID,
        LAG(STOCKITEMID) OVER (ORDER BY STOCKITEMSTOCKGROUPID) AS prev_stockitemid,
        ROW_NUMBER() OVER (ORDER BY STOCKITEMSTOCKGROUPID) AS row_num
    FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
)
SELECT 
    STOCKITEMID,
    STOCKGROUPID,
    CASE
        WHEN STOCKITEMID IS NULL THEN prev_stockitemid + 1
        ELSE STOCKITEMID
    END AS STOCKITEMID
FROM CTE
ORDER BY row_num;


----------------------------------------
-- Add foreign keys to the table
----------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD CONSTRAINT FK_STOCKITEM_STOCKGROUPS_STOCKITEMID
FOREIGN KEY (STOCKITEMID)
REFERENCES KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS(STOCKITEMID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS
ADD CONSTRAINT FK_STOCKITEM_STOCKGROUPS_STOCKGROUPID
FOREIGN KEY (STOCKGROUPID)
REFERENCES KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS(STOCKGROUPID);

