-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS AS
SELECT
  CAST(CASE WHEN STOCKGROUPID = 'NULL' THEN NULL ELSE STOCKGROUPID END AS VARCHAR(38)) AS STOCKGROUPID,
  CAST(CASE WHEN STOCKGROUPNAME = 'NULL' THEN NULL ELSE STOCKGROUPNAME END AS VARCHAR(50)) AS STOCKGROUPNAME
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS_RAW;

-- Verify the clean table
SELECT *
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS;

---------------------------------
--Conversion of datatypes
---------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
ADD COLUMN STOCKGROUPID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
SET STOCKGROUPID_NUM = CAST(STOCKGROUPID AS NUMBER(38,0));

SELECT STOCKGROUPID_NUM, STOCKGROUPID
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
DROP COLUMN STOCKGROUPID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
RENAME COLUMN STOCKGROUPID_NUM TO STOCKGROUPID;

SELECT 
    STOCKGROUPID, STOCKGROUPNAME
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
LIMIT 10;

----------------------------------------
--Addition of primary key to table
----------------------------------------

ALTER TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
ADD CONSTRAINT PK_WAREHOUSE_STOCKGROUPS_STOCKGROUPID
PRIMARY KEY (STOCKGROUPID);


-------------------------------------------
--ERROR HANDLING
-------------------------------------------
WITH CTE AS (
    SELECT 
        STOCKGROUPID,
        STOCKGROUPNAME,
        LAG(STOCKGROUPID) OVER (ORDER BY STOCKGROUPID) AS prev_stockgroupid,
        ROW_NUMBER() OVER (ORDER BY CITYID) AS row_num
    FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS
)
SELECT 
    STOCKGROUPNAME,
    CASE
        WHEN STOCKGROUPID IS NULL THEN prev_stockgroupid + 1
        ELSE STOCKGROUPID
    END AS STOCKGROUPID
FROM CTE
ORDER BY row_num;


-----------------------------------------------------
--Adding of foreign keys to the table
-----------------------------------------------------
-- THERE ARE NO FOREIGN KEYS IN THIS TABLE
