create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_COUNTRIES_SEA (
	COUNTRYID NUMBER(38,0) NOT NULL,
	COUNTRYNAME VARCHAR(16777216),
	FORMALNAME VARCHAR(16777216),
	LATESTRECORDEDPOPULATION NUMBER(38,0),
	CONTINENT VARCHAR(16777216),
	REGION VARCHAR(16777216),
	SUBREGION VARCHAR(16777216),
	constraint UK_APPLICATION_COUNTRIES_SEA_COUNTRYNAME_FORMALNAME unique (COUNTRYNAME, FORMALNAME),
	constraint PK_APPLICATION_COUNTRIES_SEA primary key (COUNTRYID)
);
