create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE (
	PERSONID VARCHAR(20) NOT NULL,
	FULLNAME VARCHAR(16777216),
	PREFERREDNAME VARCHAR(16777216),
	SEARCHNAME VARCHAR(16777216),
	ISEMPLOYEE BOOLEAN,
	ISSALESPERSON BOOLEAN,
	constraint PK_APPLICATION_PEOPLE primary key (PERSONID)
);
