create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE_RAW (
	PERSONID VARCHAR(38),
	FULLNAME VARCHAR(50),
	PREFERREDNAME VARCHAR(50),
	SEARCHNAME VARCHAR(110),
	ISEMPLOYEE VARCHAR(38),
	ISSALESPERSON VARCHAR(38)
);
