-- Create a clean table with the same structure as the raw table
create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES_RAW (
	TRANSACTIONTYPEID VARCHAR(38),
	TRANSACTIONTYPENAME VARCHAR(50)
);
