create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_CITIES_RAW (
	CITYID VARCHAR(38),
	CITYNAME VARCHAR(50),
	COUNTRYID VARCHAR(38),
	LATITUDE VARCHAR(38),
	LONGITUDE VARCHAR(38),
	LATESTRECORDEDPOPULATION VARCHAR(38)
);
