-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_COUNTRIES_SEA AS
SELECT
  CAST(CASE WHEN COUNTRYNAME = 'NULL' THEN NULL ELSE COUNTRYNAME END AS VARCHAR(60)) AS COUNTRYNAME,
  CAST(CASE WHEN FORMALNAME = 'NULL' THEN NULL ELSE FORMALNAME END AS VARCHAR(60)) AS FORMALNAME,
  CAST(CASE WHEN CONTINENT = 'NULL' THEN NULL ELSE CONTINENT END AS VARCHAR(30)) AS CONTINENT,
  CAST(CASE WHEN REGION = 'NULL' THEN NULL ELSE REGION END AS VARCHAR(30)) AS REGION,
  CAST(CASE WHEN SUBREGION = 'NULL' THEN NULL ELSE SUBREGION END AS VARCHAR(30)) AS SUBREGION,
  CAST(CASE WHEN COUNTRYID = 'NULL' THEN NULL ELSE COUNTRYID END AS VARCHAR(38)) AS COUNTRYID,
  CAST(CASE WHEN LATESTRECORDEDPOPULATION = 'NULL' THEN NULL ELSE LATESTRECORDEDPOPULATION END AS VARCHAR(38)) AS LATESTRECORDEDPOPULATION
FROM KN_LOGISTICS.SNOWSQL.APPLICATION_COUNTRIES_SEA_RAW;
