create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS (
	PAYMENTMETHODID VARCHAR(20) NOT NULL,
	PAYMENTMETHODNAME VARCHAR(16777216),
	constraint UK_APPLICATION_PAYMENTMETHODS_PAYMENTMETHODNAME unique (PAYMENTMETHODNAME),
	constraint PK_APPLICATION_PAYMENTMETHODS primary key (PAYMENTMETHODID)
);
