create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_CITIES (
	CITYID NUMBER(38,0) NOT NULL,
	CITYNAME VARCHAR(16777216),
	STATEPROVINCEID NUMBER(38,0),
	LATITUDE NUMBER(38,0),
	LONGITUDE NUMBER(38,0),
	LATESTRECORDEDPOPULATION NUMBER(38,0),
	constraint UQ_APPLICATION_CITIES_CITYNAME unique (CITYNAME),
	constraint PK_APPLICATION_CITIES primary key (CITYID)
);
