create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_COUNTRIES_SEA_RAW (
	COUNTRYID VARCHAR(38),
	COUNTRYNAME VARCHAR(60),
	FORMALNAME VARCHAR(60),
	LATESTRECORDEDPOPULATION VARCHAR(38),
	CONTINENT VARCHAR(30),
	REGION VARCHAR(30),
	SUBREGION VARCHAR(30)
);
