create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_DELIVERYMETHODS (
	DELIVERYMETHODID VARCHAR(38) NOT NULL,
	DELIVERYMETHODNAME VARCHAR(50),
	constraint UK_APPLICATION_DELIVERYMETHODS_DELIVERYMETHODNAME unique (DELIVERYMETHODNAME),
	constraint PK_APPLICATION_DELIVERYMETHODS primary key (DELIVERYMETHODID)
);
