create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES (
	TRANSACTIONTYPEID NUMBER(38,0) NOT NULL,
	TRANSACTIONTYPENAME VARCHAR(16777216),
	constraint UK_APPLICATION_TRANSACTIONTYPES_TRANSACTIONTYPENAME unique (TRANSACTIONTYPENAME),
	constraint PK_APPLICATION_TRANSACTIONTYPES primary key (TRANSACTIONTYPEID)
);
