create or replace TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_STATEPROVINCES (
	STATEPROVINCEID NUMBER(38,0) NOT NULL,
	STATEPROVINCECODE VARCHAR(16777216),
	STATEPROVINCENAME VARCHAR(16777216),
	COUNTRYID NUMBER(38,0),
	SALESTERRITORY VARCHAR(16777216),
	LATESTRECORDEDPOPULATION NUMBER(38,0),
	constraint UK_APPLICATION_STATEPROVINCES_STATEPROVINCENAME unique (STATEPROVINCENAME),
	constraint PK_APPLICATION_STATEPROVINCES primary key (STATEPROVINCEID),
	constraint FK_APPLICATION_STATEPROVINCES_COUNTRYID_APPLICATION_COUNTRIES_SEA foreign key (COUNTRYID) references KN_LOGISTICS.SNOWSQL.APPLICATION_COUNTRIES_SEA(COUNTRYID)
);
