-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE AS
SELECT
  CAST(CASE WHEN PERSONID = 'NULL' THEN NULL ELSE PERSONID END AS VARCHAR(38)) AS PERSONID,
  CAST(CASE WHEN FULLNAME = 'NULL' THEN NULL ELSE FULLNAME END AS VARCHAR(50)) AS FULLNAME,
  CAST(CASE WHEN PREFERREDNAME = 'NULL' THEN NULL ELSE PREFERREDNAME END AS VARCHAR(50)) AS PREFERREDNAME,
  CAST(CASE WHEN SEARCHNAME = 'NULL' THEN NULL ELSE SEARCHNAME END AS VARCHAR(101)) AS SEARCHNAME,
  CAST(CASE WHEN ISEMPLOYEE = 'NULL' THEN NULL ELSE ISEMPLOYEE END AS VARCHAR(38)) AS ISEMPLOYEE,
  CAST(CASE WHEN ISSALESPERSON = 'NULL' THEN NULL ELSE ISSALESPERSON END AS VARCHAR(38)) AS ISSALESPERSON
FROM KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE_RAW;
