-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.APPLICATION_CITIES AS
SELECT
  CAST(CASE WHEN CITYID = 'NULL' THEN NULL ELSE CITYID END AS VARCHAR(38)) AS CITYID,
  CAST(CASE WHEN CITYNAME = 'NULL' THEN NULL ELSE CITYNAME END AS VARCHAR(50)) AS CITYNAME,
  CAST(CASE WHEN COUNTRYID = 'NULL' THEN NULL ELSE COUNTRYID END AS VARCHAR(38)) AS COUNTRYID,
  CAST(CASE WHEN LATITUDE = 'NULL' THEN NULL ELSE LATITUDE END AS VARCHAR(38)) AS LATITUDE,
  CAST(CASE WHEN LONGITUDE = 'NULL' THEN NULL ELSE LONGITUDE END AS VARCHAR(38)) AS LONGITUDE,
  CAST(CASE WHEN LATESTRECORDEDPOPULATION = 'NULL' THEN NULL ELSE LATESTRECORDEDPOPULATION END AS VARCHAR(38)) AS LATESTRECORDEDPOPULATION
FROM KN_LOGISTICS.SNOWSQL.APPLICATION_CITIES_RAW;
