

create or replace TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS (
	SUPPLIERTRANSACTIONID NUMBER(38,0) NOT NULL ,
	SUPPLIERID VARCHAR(16777216),
	TRANSACTIONTYPEID NUMBER(38,0),
	PURCHASEORDERID VARCHAR(20),
	PAYMENTMETHODID VARCHAR(20),
	SUPPLIERINVOICENUMBER VARCHAR(20),
	TRANSACTIONDATE VARCHAR(20),
	AMOUNTEXCLUDINGTAX NUMBER(18,2),
	TAXAMOUNT NUMBER(18,2),
	TRANSACTIONAMOUNT NUMBER(18,2),
	OUTSTANDINGBALANCE NUMBER(18,2),
	FINALIZATIONDATE VARCHAR(20),
	ISFINALIZED BOOLEAN,
	primary key (SUPPLIERTRANSACTIONID),
	constraint FK_PURCHASING_SUPPLIERTRANSACTIONS_SUPPLIERID foreign key (SUPPLIERID) references KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS(SUPPLIERID),
	constraint FK_PURCHASING_SUPPLIERTRANSACTIONS_TRANSACTIONTYPEID foreign key (TRANSACTIONTYPEID) references KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES(TRANSACTIONTYPEID),
	constraint FK_PURCHASING_SUPPLIERTRANSACTIONS_PURCHASEORDERID foreign key (PURCHASEORDERID) references KN_LOGISTICS.SNOWSQL.PURCHASING_PURCHASEORDERS(PURCHASEORDERID),
	constraint FK_PURCHASING_SUPPLIERTRANSACTIONS_PAYMENTMETHODID foreign key (PAYMENTMETHODID) references KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS(PAYMENTMETHODID)
);

-- Add the foreign key constraint for SUPPLIERID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_SUPPLIERID 
FOREIGN KEY (SUPPLIERID) 
REFERENCES KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS(SUPPLIERID);

-- Add the foreign key constraint for TRANSACTIONTYPEID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_TRANSACTIONTYPEID 
FOREIGN KEY (TRANSACTIONTYPEID) 
REFERENCES KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES(TRANSACTIONTYPEID);

-- Add the foreign key constraint for PURCHASEORDERID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_PURCHASEORDERID 
FOREIGN KEY (PURCHASEORDERID) 
REFERENCES KN_LOGISTICS.SNOWSQL.PURCHASING_PURCHASEORDERS(PURCHASEORDERID);

-- Add the foreign key constraint for PAYMENTMETHODID
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD CONSTRAINT FK_PURCHASING_SUPPLIERTRANSACTIONS_PAYMENTMETHODID 
FOREIGN KEY (PAYMENTMETHODID) 
REFERENCES KN_LOGISTICS.SNOWSQL.APPLICATION_PAYMENTMETHODS(PAYMENTMETHODID);




-- Change to date format for TRANSACTIONDATE column
UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET TRANSACTIONDATE = TO_DATE(TRANSACTIONDATE, 'DD/MM/YYYY')
WHERE TRANSACTIONDATE IS NOT NULL;


// Check 10 rows of TRANSACTIONOCCURREDWHEN after updating the data type
SELECT TRANSACTIONDATE FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS LIMIT 10;

-- Change to date format for FINALIZATIONDATE column
UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET FINALIZATIONDATE = TO_DATE(FINALIZATIONDATE, 'DD/MM/YYYY')
WHERE FINALIZATIONDATE IS NOT NULL;


// Check 10 rows of TRANSACTIONOCCURREDWHEN after updating the data type
SELECT FINALIZATIONDATE FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS LIMIT 10;








-- check for 'null' for VARCHAR DATA TYPE COLUMNS ONLY
SELECT
    SUM(CASE WHEN SUPPLIERID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_SUPPLIERID,
    -- SUM(CASE WHEN TRANSACTIONTYPEID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_TRANSACTIONTYPEID,
    SUM(CASE WHEN PURCHASEORDERID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PURCHASEORDERID,
    SUM(CASE WHEN PAYMENTMETHODID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PAYMENTMETHODID,
    SUM(CASE WHEN SUPPLIERINVOICENUMBER = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_SUPPLIERINVOICENUMBER,
    SUM(CASE WHEN TRANSACTIONDATE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_TRANSACTIONDATE,
    SUM(CASE WHEN FINALIZATIONDATE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_FINALIZATIONDATE,
    -- SUM(CASE WHEN ISFINALIZED = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_ISFINALIZED
FROM 
    KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

--  check for actual null values
SELECT 
    COUNT(CASE WHEN SUPPLIERTRANSACTIONID IS NULL THEN 1 END) AS count_SUPPLIERTRANSACTIONID_NULL,
    COUNT(CASE WHEN SUPPLIERID IS NULL THEN 1 END) AS count_SUPPLIERID_NULL,
    COUNT(CASE WHEN TRANSACTIONTYPEID IS NULL THEN 1 END) AS count_TRANSACTIONTYPEID_NULL,
    COUNT(CASE WHEN PURCHASEORDERID IS NULL THEN 1 END) AS count_PURCHASEORDERID_NULL,
    COUNT(CASE WHEN PAYMENTMETHODID IS NULL THEN 1 END) AS count_PAYMENTMETHODID_NULL,
    COUNT(CASE WHEN SUPPLIERINVOICENUMBER IS NULL THEN 1 END) AS count_SUPPLIERINVOICENUMBER_NULL,
    COUNT(CASE WHEN TRANSACTIONDATE IS NULL THEN 1 END) AS count_TRANSACTIONDATE_NULL,
    COUNT(CASE WHEN AMOUNTEXCLUDINGTAX IS NULL THEN 1 END) AS count_AMOUNTEXCLUDINGTAX_NULL,
    COUNT(CASE WHEN TAXAMOUNT IS NULL THEN 1 END) AS count_TAXAMOUNT_NULL,
    COUNT(CASE WHEN TRANSACTIONAMOUNT IS NULL THEN 1 END) AS count_TRANSACTIONAMOUNT_NULL,
    COUNT(CASE WHEN OUTSTANDINGBALANCE IS NULL THEN 1 END) AS count_OUTSTANDINGBALANCE_NULL,
    COUNT(CASE WHEN FINALIZATIONDATE IS NULL THEN 1 END) AS count_FINALIZATIONDATE_NULL,
    COUNT(CASE WHEN ISFINALIZED IS NULL THEN 1 END) AS count_ISFINALIZED_NULL
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;



// convert "NULL" string values into actual null values
-----------------------------------------------------------------------------------------
-- Convert "NULL" string values into actual NULL values
UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET 
    PURCHASEORDERID = NULL,
    SUPPLIERINVOICENUMBER = NULL
WHERE 
    PURCHASEORDERID = 'NULL' OR SUPPLIERINVOICENUMBER = 'NULL';

-- change purchaseorderid to numerical data type
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN PURCHASEORDERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET PURCHASEORDERID_NUM = TO_NUMBER(PURCHASEORDERID);

SELECT PURCHASEORDERID, PURCHASEORDERID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN PURCHASEORDERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN PURCHASEORDERID_NUM TO PURCHASEORDERID;

---------------------------------------------
// data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN SUPPLIERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET SUPPLIERID_NUM = TO_NUMBER(SUPPLIERID);

SELECT SUPPLIERID, SUPPLIERID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN SUPPLIERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN SUPPLIERID_NUM TO SUPPLIERID;



--------------------------------------------------
// data type conversion (to date) FINALIZATIONDATE 
--------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN FINALIZATIONDATE_DATE DATE;


UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET FINALIZATIONDATE_DATE = TO_DATE(FINALIZATIONDATE);

SELECT FINALIZATIONDATE, FINALIZATIONDATE_DATE
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN FINALIZATIONDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN FINALIZATIONDATE_DATE TO FINALIZATIONDATE;


--------------------------------------------------
// data type conversion (to date) TRANSACTIONDATE
--------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
ADD COLUMN TRANSACTIONDATE_DATE DATE;

// Change to date format for ORDERDATE column
UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
SET TRANSACTIONDATE_DATE = TO_DATE(TRANSACTIONDATE);

SELECT TRANSACTIONDATE, TRANSACTIONDATE_DATE
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
DROP COLUMN TRANSACTIONDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS
RENAME COLUMN TRANSACTIONDATE_DATE TO TRANSACTIONDATE;

SELECT * FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS LIMIT 10;


