create or replace TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERCATEGORIES (
	SUPPLIERCATEGORYID NUMBER(38,0),
	SUPPLIERCATEGORYNAME VARCHAR(16777216),
	constraint PK_PURCHASING_SUPPLIERCATEGORIE primary key (SUPPLIERCATEGORYID)
);

