create or replace TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERTRANSACTIONS_RAW (
	SUPPLIERTRANSACTIONID VARCHAR(38),
	SUPPLIERID VARCHAR(38),
	TRANSACTIONTYPEID VARCHAR(38),
	PURCHASEORDERID VARCHAR(38),
	PAYMENTMETHODID VARCHAR(38),
	SUPPLIERINVOICENUMBER VARCHAR(20),
	TRANSACTIONDATE VARCHAR(20),
	AMOUNTEXCLUDINGTAX VARCHAR(38),
	TAXAMOUNT VARCHAR(38),
	TRANSACTIONAMOUNT VARCHAR(38),
	OUTSTANDINGBALANCE VARCHAR(38),
	FINALIZATIONDATE VARCHAR(20),
	ISFINALIZED VARCHAR(38)
);
