create or replace TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_PURCHASEORDERS (
	PURCHASEORDERID VARCHAR(20) NOT NULL,
	SUPPLIERID VARCHAR(16777216),
	ORDERDATE VARCHAR(20),
	DELIVERYMETHODID VARCHAR(16777216),
	CONTACTPERSONID VARCHAR(20),
	EXPECTEDDELIVERYDATE VARCHAR(20),
	SUPPLIERREFERENCE VARCHAR(16777216),
	ISORDERFINALIZED BOOLEAN,
	primary key (PURCHASEORDERID),
	constraint FK_PURCHASING_PURCHASEORDERS_DELIVERYMETHODID_APPLICATION_DELIVERYMETHODS foreign key (DELIVERYMETHODID) references KN_LOGISTICS.SNOWSQL.APPLICATION_DELIVERYMETHODS(DELIVERYMETHODID),
	constraint FK_PURCHASING_PURCHASEORDERS_CONTACTPERSONID_APPLICATION_PEOPLE foreign key (CONTACTPERSONID) references KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE(PERSONID),
	constraint FK_PURCHASING_PURCHASEORDERS_SUPPLIERID_PURCHASING_SUPPLIERS foreign key (SUPPLIERID) references KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS(SUPPLIERID)
);
