create or replace TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS (
	SUPPLIERID VARCHAR(16777216) NOT NULL,
	SUPPLIERNAME VARCHAR(16777216),
	SUPPLIERCATEGORYID NUMBER(38,0),
	PRIMARYCONTACTPERSONID NUMBER(38,0),
	ALTERNATECONTACTPERSONID NUMBER(38,0),
	DELIVERYMETHODID VARCHAR(16777216), -- Chnage to Number(38,0) and add IS NULL as NULL means none
	-- DELIVERYCITYID NUMBER(38,0), -- ocnsidering to drop
	-- POSTALCITYID NUMBER(38,0),
	SUPPLIERREFERENCE VARCHAR(20),
	PAYMENTDAYS NUMBER(38,0),
	PHONENUMBER VARCHAR(16777216),
	WEBSITEURL VARCHAR(16777216),
	-- DELIVERYADDRESSLINE VARCHAR(16777216),
	-- DELIVERYLOCATIONLAT NUMBER(38,0),
	-- DELIVERYLOCATIONLONG NUMBER(38,0),
	constraint UQ_PURCHASING_SUPPLIERS unique (SUPPLIERNAME),
	constraint PK_PURCHASING_SUPPLIERS primary key (SUPPLIERID),
	constraint FK_PURCHASING_SUPPLIERS_DELIVERYCITYID_APPLICATION_CITIES foreign key (DELIVERYCITYID) references KN_LOGISTICS.SNOWSQL.APPLICATION_CITIES(CITYID),
	constraint FK_PURCHASING_SUPPLIERS_POSTALCITYID_APPLICATION_CITIES foreign key (POSTALCITYID) references KN_LOGISTICS.SNOWSQL.APPLICATION_CITIES(CITYID),
	constraint FK_PURCHASING_SUPPLIERS_DELIVERYMETHODID_APPLICATION_DELIVERYMETHODS foreign key (DELIVERYMETHODID) references KN_LOGISTICS.SNOWSQL.APPLICATION_DELIVERYMETHODS(DELIVERYMETHODID),
	constraint FK_PURCHASING_SUPPLIERS_SUPPLIERCATEGORYID_PURCHASING_SUPPLIERCATEGORIES foreign key (SUPPLIERCATEGORYID) references KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERCATEGORIES(SUPPLIERCATEGORYID)
);


SELECT * FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

-- Handle remaining NULL values in DeliveryMethodID
UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS 
SET DELIVERYMETHODID = 11 -- None
WHERE DELIVERYMETHODID = 'NULL';

SELECT * FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS WHERE DELIVERYMETHODID = 'NULL';


-- DROPPING 5 COUMNS - DELIVERYCITYID, POSTALCITYID, DELIVERYADDRESSLINE, DELIVERYLOCATIONLAT

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN DELIVERYCITYID, POSTALCITYID, DELIVERYADDRESSLINE, DELIVERYLOCATIONLAT, DELIVERYLOCATIONLONG;


-- Convert deliverymethodid to numerical
---------------------------------------------
// data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN SUPPLIERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET SUPPLIERID_NUM = TO_NUMBER(SUPPLIERID);

SELECT SUPPLIERID, SUPPLIERID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN SUPPLIERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN SUPPLIERID_NUM TO SUPPLIERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD CONSTRAINT PK_PURCHASING_SUPPLIERS_SUPPLIERID
PRIMARY KEY (SUPPLIERID);


-- Convert supplierid to numerical
---------------------------------------------
// data type conversion (to number)
---------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
ADD COLUMN DELIVERYMETHODID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
SET DELIVERYMETHODID_NUM = TO_NUMBER(DELIVERYMETHODID);

SELECT DELIVERYMETHODID, DELIVERYMETHODID_NUM
FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
DROP COLUMN DELIVERYMETHODID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS
RENAME COLUMN DELIVERYMETHODID_NUM TO DELIVERYMETHODID;


SELECT * FROM KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS LIMIT 10;

