create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_ORDERLINES (
	ORDERLINEID NUMBER(38,0) NOT NULL,
	ORDERID NUMBER(38,0),
	STOCKITEMID NUMBER(38,0),
	DESCRIPTION VARCHAR(100),
	PACKAGETYPEID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNITPRICE FLOAT,
	TAXRATE FLOAT,
	PICKEDQUANTITY NUMBER(38,0),
	PICKINGCOMPLETEDWHEN TIMESTAMP_NTZ(9),
	primary key (ORDERLINEID),
	constraint FK_SALES_ORDERLINES_PACKAGETYPEID_WAREHOUSE_PACKAGETYPES foreign key (PACKAGETYPEID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES(PACKAGETYPEID),
	constraint FK_SALES_ORDERLINES_ORDERID_SALES_ORDERS foreign key (ORDERID) references KN_LOGISTICS.SNOWSQL.SALES_ORDERS(ORDERID),
	constraint FK_SALES_ORDERLINES_STOCKITEMID_WAREHOUSE_STOCKITEMS foreign key (STOCKITEMID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS(STOCKITEMID)
);
