create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS_RAW (
	CUSTOMERID VARCHAR(38) NOT NULL,
	CUSTOMERNAME VARCHAR(100),
	BILLTOCUSTOMERID VARCHAR(38),
	CUSTOMERCATEGORYID VARCHAR(38),
	BUYINGGROUPID VARCHAR(38),
	PRIMARYCONTACTPERSONID VARCHAR(38),
	ALTERNATECONTACTPERSONID VARCHAR(38),
	DELIVERYMETHODID VARCHAR(38),
	DELIVERYCITYID VARCHAR(38),
	CREDITLIMIT VARCHAR(38),
	ACCOUNTOPENEDDATE VARCHAR(20),
	STANDARDDISCOUNTPERCENTAGE VARCHAR(38),
	ISSTATEMENTSENT VARCHAR(38),
	ISONCREDITHOLD VARCHAR(38),
	PAYMENTDAYS VARCHAR(38),
	PHONENUMBER VARCHAR(20),
	WEBSITEURL VARCHAR(256)
);
