create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_INVOICELINES (
	INVOICELINEID NUMBER(38,0) NOT NULL,
	INVOICEID NUMBER(38,0),
	STOCKITEMID NUMBER(38,0),
	DESCRIPTION VARCHAR(16777216),
	PACKAGETYPEID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	UNITPRICE FLOAT,
	TAXRATE FLOAT,
	TAXAMOUNT FLOAT,
	LINEPROFIT FLOAT,
	EXTENDEDPRICE FLOAT,
	primary key (INVOICELINEID),
	constraint FK_SALES_INVOICELINES_PACKAGETYPEID_WAREHOUSE_PACKAGETYPES foreign key (PACKAGETYPEID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_PACKAGETYPES(PACKAGETYPEID),
	constraint FK_SALES_INVOICELINES_STOCKITEMID_WAREHOUSE_STOCKITEMS foreign key (STOCKITEMID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS(STOCKITEMID)
);
