create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_ORDERLINES_RAW (
	ORDERLINEID VARCHAR(38) NOT NULL,
	ORDERID VARCHAR(38),
	STOCKITEMID VARCHAR(38),
	DESCRIPTION VARCHAR(100),
	PACKAGETYPEID VARCHAR(38),
	QUANTITY VARCHAR(38),
	UNITPRICE VARCHAR(38),
	TAXRATE VARCHAR(38),
	PICKEDQUANTITY VARCHAR(38),
	PICKINGCOMPLETEDWHEN VARCHAR(25)
);
