create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_INVOICELINES_RAW (
	INVOICELINEID VARCHAR(38) NOT NULL,
	INVOICEID VARCHAR(38),
	STOCKITEMID VARCHAR(38),
	DESCRIPTION VARCHAR(100),
	PACKAGETYPEID VARCHAR(38),
	QUANTITY VARCHAR(38),
	UNITPRICE VARCHAR(38),
	TAXRATE VARCHAR(38),
	TAXAMOUNT VARCHAR(38),
	LINEPROFIT VARCHAR(38),
	EXTENDEDPRICE VARCHAR(38)
);
