create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_ORDERS (
	ORDERID VARCHAR(16777216) NOT NULL,
	CUSTOMERID VARCHAR(16777216),
	SALESPERSONPERSONID VARCHAR(20),
	PICKEDBYPERSONID VARCHAR(20),
	CONTACTPERSONID VARCHAR(20),
	BACKORDERORDERID VARCHAR(16777216),
	ORDERDATE VARCHAR(16777216),
	EXPECTEDDELIVERYDATE VARCHAR(16777216),
	CUSTOMERPURCHASEORDERNUMBER VARCHAR(16777216),
	ISUNDERSUPPLYBACKORDERED BOOLEAN,
	PICKINGCOMPLETEDWHEN VARCHAR(16777216),
	constraint PK_SALES_ORDERS primary key (ORDERID),
	constraint FK_SALES_ORDERS_BACKORDERORDERID_SALES_ORDERS foreign key (BACKORDERORDERID) references KN_LOGISTICS.SNOWSQL.SALES_ORDERS(ORDERID),
	constraint FK_SALES_ORDERS_CONTACTPERSONID_APPLICATION_PEOPLE foreign key (CONTACTPERSONID) references KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE(PERSONID),
	constraint FK_SALES_ORDERS_PICKEDBYPERSONID_APPLICATION_PEOPLE foreign key (PICKEDBYPERSONID) references KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE(PERSONID),
	constraint FK_SALES_ORDERS_SALESPERSONPERSONID_APPLICATION_PEOPLE foreign key (SALESPERSONPERSONID) references KN_LOGISTICS.SNOWSQL.APPLICATION_PEOPLE(PERSONID),
	constraint FK_SALES_ORDERS_CUSTOMERID_SALES_CUSTOMERS foreign key (CUSTOMERID) references KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS(CUSTOMERID)
);
