create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERCATEGORIES (
	CUSTOMERCATEGORYID VARCHAR(38),
	CUSTOMERCATEGORYNAME VARCHAR(50),
	constraint PK_SALES_CUSTOMERCATEGORIES_CUSTOMERCATEGORYID primary key (CUSTOMERCATEGORYID),
	constraint UK_SALES_CUSTOMERCATEGORIES_CUSTOMERCATEGORYNAME unique (CUSTOMERCATEGORYNAME)
);
