create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERCATEGORIES (
	CUSTOMERCATEGORYID NUMBER(38,0) NOT NULL,
	CUSTOMERCATEGORYNAME VARCHAR(16777216),
	constraint UK_SALES_CUSTOMERCATEGORIES_CUSTOMERCATEGORYNAME unique (CUSTOMERCATEGORYNAME),
	constraint PK_SALES_CUSTOMERCATEGORIES primary key (CUSTOMERCATEGORYID)
);
