create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_INVOICES (
	INVOICEID NUMBER(38,0) NOT NULL,
	CUSTOMERID NUMBER(38,0),
	BILLTOCUSTOMERID NUMBER(38,0),
	ORDERID NUMBER(38,0),
	DELIVERYMETHODID NUMBER(38,0),
	CONTACTPERSONID NUMBER(38,0),
	ACCOUNTSPERSONID NUMBER(38,0),
	SALESPERSONPERSONID NUMBER(38,0),
	PACKEDBYPERSONID NUMBER(38,0),
	INVOICEDATE DATE,
	CUSTOMERPURCHASEORDERNUMBER NUMBER(38,0),
	TOTALDRYITEMS NUMBER(38,0),
	TOTALCHILLERITEMS NUMBER(38,0),
	CONFIRMEDDELIVERYTIME TIMESTAMP_NTZ(9),
	CONFIRMEDRECEIVEDBY VARCHAR(4000),
	constraint PK_SALES_INVOICES primary key (INVOICEID),
	constraint FK_SALES_INVOICES_ORDERID_SALES_ORDERS foreign key (ORDERID) references KN_LOGISTICS.SNOWSQL.SALES_ORDERS(ORDERID),
	constraint FK_SALES_INVOICES_DELIVERYMETHODID_APPLICATION_DELIVERYMETHODS foreign key (DELIVERYMETHODID) references KN_LOGISTICS.SNOWSQL.APPLICATION_DELIVERYMETHODS(DELIVERYMETHODID)
);




