create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS (
	CUSTOMERTRANSACTIONID NUMBER(38,0) NOT NULL,
	CUSTOMERID VARCHAR(16777216),-- CHANGES CUSTOEMRID TO VARCHAR(16777216) FROM NUMBER(38,0)
	TRANSACTIONTYPEID NUMBER(38,0),
	INVOICEID VARCHAR(20),
	PAYMENTMETHODID VARCHAR(20),
	TRANSACTIONDATE VARCHAR(20),
	AMOUNTEXCLUDINGTAX FLOAT,
	TAXAMOUNT FLOAT,
	TRANSACTIONAMOUNT FLOAT,
	OUTSTANDINGBALANCE FLOAT,
	FINALIZATIONDATE VARCHAR(20),
	ISFINALIZED BOOLEAN,
	constraint PK_SALES_CUSTOMERTRANSACTIONS primary key (CUSTOMERTRANSACTIONID)

);





ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD CONSTRAINT FK_CUSTOMERTRANSACTIONS_INVOICEID
FOREIGN KEY (INVOICEID)
REFERENCES KN_LOGISTICS.SNOWSQL.SALES_INVOICES (INVOICEID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD CONSTRAINT FK_CUSTOMERTRANSACTIONS_TRANSACTIONTYPEID
FOREIGN KEY (TRANSACTIONTYPEID)
REFERENCES KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES (TRANSACTIONTYPEID);

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD CONSTRAINT FK_CUSTOMERTRANSACTIONS_CUSTOMERID
FOREIGN KEY (CUSTOMERID)
REFERENCES KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS (CUSTOMERID);






-- Change to date format for TRANSACTIONDATE column
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET TRANSACTIONDATE = TO_DATE(TRANSACTIONDATE, 'DD/MM/YYYY')
WHERE TRANSACTIONDATE IS NOT NULL;


// Check 10 rows of TRANSACTIONOCCURREDWHEN after updating the data type
SELECT TRANSACTIONDATE FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS LIMIT 10;

-- Change to date format for FINALIZATIONDATE column
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET FINALIZATIONDATE = TO_DATE(FINALIZATIONDATE, 'DD/MM/YYYY')
WHERE FINALIZATIONDATE IS NOT NULL;


// Check 10 rows of TRANSACTIONOCCURREDWHEN after updating the data type
SELECT FINALIZATIONDATE FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS LIMIT 10;

-- Handle remaining NULL values in DeliveryMethodID
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET PAYMENTMETHODID = 5 -- oTHERS
WHERE PAYMENTMETHODID = 'NULL';

SELECT
    SUM(CASE WHEN CUSTOMERID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_CUSTOMERID,
    -- SUM(CASE WHEN TRANSACTIONTYPEID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_TRANSACTIONTYPEID,
    SUM(CASE WHEN INVOICEID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_INVOICEID,
    SUM(CASE WHEN PAYMENTMETHODID = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_PAYMENTMETHODID,
    SUM(CASE WHEN TRANSACTIONDATE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_TRANSACTIONDATE,
    SUM(CASE WHEN FINALIZATIONDATE = 'NULL' THEN 1 ELSE 0 END) AS NULL_COUNT_FINALIZATIONDATE
FROM 
    KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;





-- Handle remaining NULL values in invoiceid
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET INVOICEID = NULL -- oTHERS
WHERE INVOICEID = 'NULL';

-- change invoiceid to numerical data type
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD COLUMN INVOICEID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET INVOICEID_NUM = TO_NUMBER(INVOICEID);

SELECT INVOICEID, INVOICEID_NUM
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
DROP COLUMN INVOICEID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
RENAME COLUMN INVOICEID_NUM TO INVOICEID;


-- change paymentmethodid to numerical data type
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD COLUMN PAYMENTMETHODID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET PAYMENTMETHODID_NUM = TO_NUMBER(PAYMENTMETHODID);

SELECT PAYMENTMETHODID, PAYMENTMETHODID_NUM
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
DROP COLUMN PAYMENTMETHODID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
RENAME COLUMN PAYMENTMETHODID_NUM TO PAYMENTMETHODID;


SELECT 
    COUNT(CASE WHEN CUSTOMERID IS NULL THEN 1 END) AS count_CUSTOMERID_NULL,
    COUNT(CASE WHEN TRANSACTIONTYPEID IS NULL THEN 1 END) AS count_TRANSACTIONTYPEID_NULL,
    COUNT(CASE WHEN INVOICEID IS NULL THEN 1 END) AS count_INVOICEID_NULL,
    COUNT(CASE WHEN PAYMENTMETHODID IS NULL THEN 1 END) AS count_PAYMENTMETHODID_NULL,
    COUNT(CASE WHEN TRANSACTIONDATE IS NULL THEN 1 END) AS count_TRANSACTIONDATE_NULL,
    COUNT(CASE WHEN AMOUNTEXCLUDINGTAX IS NULL THEN 1 END) AS count_AMOUNTEXCLUDINGTAX_NULL,
    COUNT(CASE WHEN TAXAMOUNT IS NULL THEN 1 END) AS count_TAXAMOUNT_NULL,
    COUNT(CASE WHEN TRANSACTIONAMOUNT IS NULL THEN 1 END) AS count_TRANSACTIONAMOUNT_NULL,
    COUNT(CASE WHEN OUTSTANDINGBALANCE IS NULL THEN 1 END) AS count_OUTSTANDINGBALANCE_NULL,
    COUNT(CASE WHEN FINALIZATIONDATE IS NULL THEN 1 END) AS count_FINALIZATIONDATE_NULL,
    COUNT(CASE WHEN ISFINALIZED IS NULL THEN 1 END) AS count_ISFINALIZED_NULL
FROM 
    KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;


--------------------------------------------------
// data type conversion (to date) FINALIZATIONDATE 
--------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD COLUMN FINALIZATIONDATE_DATE DATE;

// Change to date format for ORDERDATE column
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET FINALIZATIONDATE_DATE = TO_DATE(FINALIZATIONDATE);

SELECT FINALIZATIONDATE, FINALIZATIONDATE_DATE
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
DROP COLUMN FINALIZATIONDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
RENAME COLUMN FINALIZATIONDATE_DATE TO FINALIZATIONDATE;




--------------------------------------------------
// data type conversion (to date) TRANSACTIONDATE
--------------------------------------------------
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD COLUMN TRANSACTIONDATE_DATE DATE;

// Change to date format for ORDERDATE column
UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET TRANSACTIONDATE_DATE = TO_DATE(TRANSACTIONDATE);

SELECT TRANSACTIONDATE, TRANSACTIONDATE_DATE
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
DROP COLUMN TRANSACTIONDATE;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
RENAME COLUMN TRANSACTIONDATE_DATE TO TRANSACTIONDATE;


--------------------------------------------------
// data type conversion (to NUMBER) CUSTOMERID
--------------------------------------------------
-- change invoiceid to numerical data type
ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
ADD COLUMN CUSTOMERID_NUM NUMBER(38,0);

UPDATE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
SET CUSTOMERID_NUM = TO_NUMBER(CUSTOMERID);

SELECT CUSTOMERID, CUSTOMERID_NUM
FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
DROP COLUMN CUSTOMERID;

ALTER TABLE KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS
RENAME COLUMN CUSTOMERID_NUM TO CUSTOMERID;

SELECT * FROM KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERTRANSACTIONS LIMIT 10;


