create or replace TABLE KN_LOGISTICS.SNOWSQL.SALES_INVOICES_RAW (
	INVOICEID VARCHAR(38),
	CUSTOMERID VARCHAR(38),
	BILLTOCUSTOMERID VARCHAR(38),
	ORDERID VARCHAR(38),
	DELIVERYMETHODID VARCHAR(38),
	CONTACTPERSONID VARCHAR(38),
	ACCOUNTSPERSONID VARCHAR(38),
	SALESPERSONPERSONID VARCHAR(38),
	PACKEDBYPERSONID VARCHAR(38),
	INVOICEDATE VARCHAR(20),
	CUSTOMERPURCHASEORDERNUMBER VARCHAR(20),
	TOTALDRYITEMS VARCHAR(38),
	TOTALCHILLERITEMS VARCHAR(38),
	CONFIRMEDDELIVERYTIME VARCHAR(25),
	CONFIRMEDRECEIVEDBY VARCHAR(4000)
);
