create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMSTOCKGROUPS (
	STOCKITEMSTOCKGROUPID NUMBER(38,0) NOT NULL,
	STOCKITEMID NUMBER(38,0),
	STOCKGROUPID NUMBER(38,0),
	constraint UQ_STOCKITEMSTOCKGROUPS_STOCKGROUPID_LOOKUP unique (STOCKGROUPID, STOCKITEMID),
	constraint UQ_STOCKITEMSTOCKGROUPS_STOCKITEMID_LOOKUP unique (STOCKITEMID, STOCKGROUPID),
	primary key (STOCKITEMSTOCKGROUPID),
	constraint FK_WAREHOUSE_STOCKITEMSTOCKGROUPS_STOCKGROUPID_WAREHOUSE_STOCKGROUPS foreign key (STOCKGROUPID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKGROUPS(STOCKGROUPID),
	constraint FK_WAREHOUSE_STOCKITEMSTOCKGROUPS_STOCKITEMID_WAREHOUSE_STOCKITEMS foreign key (STOCKITEMID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS(STOCKITEMID)
);
