create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMTRANSACTIONS (
	STOCKITEMTRANSACTIONID NUMBER(38,0) NOT NULL,
	STOCKITEMID NUMBER(38,0),
	TRANSACTIONTYPEID NUMBER(38,0),
	CUSTOMERID VARCHAR(16777216),
	INVOICEID VARCHAR(20),
	SUPPLIERID VARCHAR(16777216),
	PURCHASEORDERID VARCHAR(20),
	TRANSACTIONOCCURREDWHEN VARCHAR(16777216),
	QUANTITY FLOAT,
	constraint PK_STOCKITEMTRANSACTIONS primary key (STOCKITEMTRANSACTIONID),
	constraint FK_WAREHOUSE_STOCKITEMTRANSACTIONS_PURCHASEORDERID_PURCHASING_PURCHASEORDERS foreign key (PURCHASEORDERID) references KN_LOGISTICS.SNOWSQL.PURCHASING_PURCHASEORDERS(PURCHASEORDERID),
	constraint FK_WAREHOUSE_STOCKITEMTRANSACTIONS_STOCKITEMID_WAREHOUSE_STOCKITEMS foreign key (STOCKITEMID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS(STOCKITEMID),
	constraint FK_WAREHOUSE_STOCKITEMTRANSACTIONS_CUSTOMERID_SALES_CUSTOMERS foreign key (CUSTOMERID) references KN_LOGISTICS.SNOWSQL.SALES_CUSTOMERS(CUSTOMERID),
	constraint FK_WAREHOUSE_STOCKITEMTRANSACTIONS_SUPPLIERID_PURCHASING_SUPPLIERS foreign key (SUPPLIERID) references KN_LOGISTICS.SNOWSQL.PURCHASING_SUPPLIERS(SUPPLIERID),
    constraint FK_WAREHOUSE_STOCKITEMTRANSACTIONS_TRANSACTIONTYPEID_APPLICATION_TRANSACTIONTYPES foreign key (TRANSACTIONTYPEID) references KN_LOGISTICS.SNOWSQL.APPLICATION_TRANSACTIONTYPES(TRANSACTIONTYPEID),
	constraint FK_WAREHOUSE_STOCKITEMTRANSACTIONS_INVOICEID_SALES_INVOICES foreign key (INVOICEID) references KN_LOGISTICS.SNOWSQL.SALES_INVOICES(INVOICEID)
);
