create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMTRANSACTIONS_RAW (
	STOCKITEMTRANSACTIONID VARCHAR(38),
	STOCKITEMID VARCHAR(38),
	TRANSACTIONTYPEID VARCHAR(38),
	CUSTOMERID VARCHAR(38),
	INVOICEID VARCHAR(38),
	SUPPLIERID VARCHAR(38),
	PURCHASEORDERID VARCHAR(38),
	TRANSACTIONOCCURREDWHEN VARCHAR(25),
	QUANTITY VARCHAR(38)
);
