create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS (
	COLORID VARCHAR(16777216) NOT NULL,
	COLORNAME VARCHAR(20),
	unique (COLORNAME),
	primary key (COLORID),
	constraint FK_WAREHOUSE_PACKAGETYPE_COLORID foreign key (COLORID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS(COLORID),
	constraint FK_WAREHOUSE_STOCKITEMS_COLORID_WAREHOUSE_COLORS foreign key (COLORID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLORS(COLORID)
);
