create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS_RAW (
	STOCKITEMID VARCHAR(38),
	STOCKITEMNAME VARCHAR(100),
	SUPPLIERID VARCHAR(38),
	COLORID VARCHAR(38),
	UNITPACKAGEID VARCHAR(38),
	OUTERPACKAGEID VARCHAR(38),
	BRAND VARCHAR(50),
	SIZE VARCHAR(20),
	LEADTIMEDAYS VARCHAR(38),
	QUANTITYPEROUTER VARCHAR(38),
	ISCHILLERSTOCK VARCHAR(38),
	BARCODE VARCHAR(50),
	TAXRATE VARCHAR(38),
	UNITPRICE VARCHAR(38),
	RECOMMENDEDRETAILPRICE VARCHAR(38),
	TYPICALWEIGHTPERUNIT VARCHAR(38)
);
