create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMHOLDINGS (
	STOCKITEMID NUMBER(38,0) NOT NULL,
	QUANTITYONHAND NUMBER(38,0),
	BINLOCATION VARCHAR(16777216),
	LASTSTOCKTAKEQUANTITY NUMBER(38,0),
	LASTCOSTPRICE FLOAT,
	REORDERLEVEL NUMBER(38,0),
	TARGETSTOCKLEVEL NUMBER(38,0),
	constraint PK_STOCKITEMHOLDINGS primary key (STOCKITEMID),
    constraint 
    FK_WAREHOUSE_STOCKITEMHOLDINGS_STOCKITEMID_WAREHOUSE_STOCKITEMS foreign key (STOCKITEMID) references KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMS(STOCKITEMID)
);
