-- Create a clean table with the same structure as the raw table
CREATE OR REPLACE TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLDROOMTEMPERATURES AS
SELECT
  CAST(CASE WHEN COLDROOMTEMPERATUREID = 'NULL' THEN NULL ELSE COLDROOMTEMPERATUREID END AS VARCHAR(38)) AS COLDROOMTEMPERATUREID,
  CAST(CASE WHEN COLDROOMSENSORNUMBER = 'NULL' THEN NULL ELSE COLDROOMSENSORNUMBER END AS VARCHAR(38)) AS COLDROOMSENSORNUMBER,
  CAST(CASE WHEN RECORDEDWHEN = 'NULL' THEN NULL ELSE RECORDEDWHEN END AS VARCHAR(25)) AS RECORDEDWHEN,
  CAST(CASE WHEN TEMPERATURE = 'NULL' THEN NULL ELSE TEMPERATURE END AS VARCHAR(38)) AS TEMPERATURE
FROM KN_LOGISTICS.SNOWSQL.WAREHOUSE_COLDROOMTEMPERATURES_RAW;
