create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_VEHICLETEMPERATURES (
	VEHICLETEMPERATUREID NUMBER(38,0) NOT NULL,
	VEHICLEREGISTRATION VARCHAR(255),
	CHILLERSENSORNUMBER NUMBER(38,0),
	RECORDEDWHEN TIMESTAMP_NTZ(9),
	TEMPERATURE FLOAT,
	FULLSENSORDATA VARCHAR(16777216),
	primary key (VEHICLETEMPERATUREID)
);
