create or replace TABLE KN_LOGISTICS.SNOWSQL.WAREHOUSE_STOCKITEMHOLDINGS_RAW (
	STOCKITEMID VARCHAR(38),
	QUANTITYONHAND VARCHAR(38),
	BINLOCATION VARCHAR(20),
	LASTSTOCKTAKEQUANTITY VARCHAR(38),
	LASTCOSTPRICE VARCHAR(38),
	REORDERLEVEL VARCHAR(38),
	TARGETSTOCKLEVEL VARCHAR(38)
);
