name: Deploy Snowpark Apps

# Controls when the action will run.
on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  #schedule:
    #- cron: "*/5 * * * *"  # Optionally, run every 5 minutes (UTC time)

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runner environment for executing the job

    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python.
      - name: Setup Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Step 3: Install required Python packages.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install snowflake-connector-python
          pip install snowflake-snowpark-python
          pip install nbconvert  # For executing Jupyter notebooks
          pip install jupyter

      # Step 4: Execute Jupyter Notebook without saving output.
      - name: Execute Jupyter Notebook
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          jupyter nbconvert --to notebook --execute notebook/snowpark_notebook.ipynb --stdout > /dev/null
