name: Deploy Airflow DAG to Astronomer

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          pip install apache-airflow-providers-snowflake  # Snowflake integration

      - name: Install Astronomer CLI
        run: |
          curl -sSL https://install.astronomer.io | bash
          export PATH=$PATH:$HOME/.astro/bin

      - name: Deploy DAG
        run: |
          astro deploy
        env:
          ASTRO_API_KEY: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNsb2Q0aGtqejAya3AwMWozdWNqbzJwOHIiLCJ0eXAiOiJKV1QifQ.eyJhcGlUb2tlbklkIjoiY201eXd0YjV2MDczOTAxbmM0d2FwOTUzMyIsImF1ZCI6ImFzdHJvbm9tZXItZWUiLCJpYXQiOjE3MzcwMDY0ODYsImlzQXN0cm9ub21lckdlbmVyYXRlZCI6dHJ1ZSwiaXNJbnRlcm5hbCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYXBpLmFzdHJvbm9tZXIuaW8iLCJraWQiOiJjbG9kNGhranowMmtwMDFqM3Vjam8ycDhyIiwicGVybWlzc2lvbnMiOlsiYXBpVG9rZW5JZDpjbTV5d3RiNXYwNzM5MDFuYzR3YXA5NTMzIiwiZGVwbG95bWVudElkOmNtNXl1OTJmNjA2cnowMWtoNm91NmZndmIiLCJvcmdhbml6YXRpb25JZDpjbTV3OGRobDcxNHpxMDFsbWlqbWJxZ3JuIiwib3JnU2hvcnROYW1lOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4iLCJ3b3Jrc3BhY2VJZDpjbTV3OGRqMTAxNHp4MDFsbXphazR4MTI5Il0sInNjb3BlIjoiYXBpVG9rZW5JZDpjbTV5d3RiNXYwNzM5MDFuYzR3YXA5NTMzIGRlcGxveW1lbnRJZDpjbTV5dTkyZjYwNnJ6MDFraDZvdTZmZ3ZiIG9yZ2FuaXphdGlvbklkOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4gb3JnU2hvcnROYW1lOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4iLCJzdWIiOiJjbTV3OGN0bmgwZWVjMDFsaHZwaDhmeGFzIiwidmVyc2lvbiI6ImNtNXl3dGI1djA3MzgwMW5jeHEyd24xMmwifQ.rONseJ2LipMeKDC7mJJir6Askgr1TxtoU1JHAArt2dtuhFUUPyoTUSGfvB7rl1PtlH8U9aOFvXPOa9RFy8K4KGD9ybEnqedZtpVXTHBug2lNLIT6JZmcJpgJBAc4WuRDe2G5wypHFX1sDVqg7N7Y6zir6HYDMBHPGcks53WtbAZ-JiVmpyfXgfwrstUD44TsdVgl2tEnMFotMEDk3Eo-FIst6gMXRXSiEwm08tmFAV0K2cLD83VnR3sCuMCkIfNmaGEgsW1Y1PGKt5K0_bo832WDIbd6z0Ci0n1QaL2wyFUULWiKhHrzsyHPwgGdV5TbRIHgLOzt7bag7dYeWoA92w"  # Add API key for authentication

      
      #- name: Deploy DAG to Astronomer
       # run: |
          # You can use Astronomer's CLI or Astronomer API to upload your DAG to the Astronomer environment
          # Example for Astronomer CLI (install it first):
        #  astronaut login --api-token eyJhbGciOiJSUzI1NiIsImtpZCI6ImNsb2Q0aGtqejAya3AwMWozdWNqbzJwOHIiLCJ0eXAiOiJKV1QifQ.eyJhcGlUb2tlbklkIjoiY201eXd0YjV2MDczOTAxbmM0d2FwOTUzMyIsImF1ZCI6ImFzdHJvbm9tZXItZWUiLCJpYXQiOjE3MzcwMDY0ODYsImlzQXN0cm9ub21lckdlbmVyYXRlZCI6dHJ1ZSwiaXNJbnRlcm5hbCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vYXBpLmFzdHJvbm9tZXIuaW8iLCJraWQiOiJjbG9kNGhranowMmtwMDFqM3Vjam8ycDhyIiwicGVybWlzc2lvbnMiOlsiYXBpVG9rZW5JZDpjbTV5d3RiNXYwNzM5MDFuYzR3YXA5NTMzIiwiZGVwbG95bWVudElkOmNtNXl1OTJmNjA2cnowMWtoNm91NmZndmIiLCJvcmdhbml6YXRpb25JZDpjbTV3OGRobDcxNHpxMDFsbWlqbWJxZ3JuIiwib3JnU2hvcnROYW1lOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4iLCJ3b3Jrc3BhY2VJZDpjbTV3OGRqMTAxNHp4MDFsbXphazR4MTI5Il0sInNjb3BlIjoiYXBpVG9rZW5JZDpjbTV5d3RiNXYwNzM5MDFuYzR3YXA5NTMzIGRlcGxveW1lbnRJZDpjbTV5dTkyZjYwNnJ6MDFraDZvdTZmZ3ZiIG9yZ2FuaXphdGlvbklkOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4gb3JnU2hvcnROYW1lOmNtNXc4ZGhsNzE0enEwMWxtaWptYnFncm4iLCJzdWIiOiJjbTV3OGN0bmgwZWVjMDFsaHZwaDhmeGFzIiwidmVyc2lvbiI6ImNtNXl3dGI1djA3MzgwMW5jeHEyd24xMmwifQ.rONseJ2LipMeKDC7mJJir6Askgr1TxtoU1JHAArt2dtuhFUUPyoTUSGfvB7rl1PtlH8U9aOFvXPOa9RFy8K4KGD9ybEnqedZtpVXTHBug2lNLIT6JZmcJpgJBAc4WuRDe2G5wypHFX1sDVqg7N7Y6zir6HYDMBHPGcks53WtbAZ-JiVmpyfXgfwrstUD44TsdVgl2tEnMFotMEDk3Eo-FIst6gMXRXSiEwm08tmFAV0K2cLD83VnR3sCuMCkIfNmaGEgsW1Y1PGKt5K0_bo832WDIbd6z0Ci0n1QaL2wyFUULWiKhHrzsyHPwgGdV5TbRIHgLOzt7bag7dYeWoA92w
         # astronaut airflow deploy --image 12.6.0 --deploy-dag dag.py
          
          # If using Astronomer API directly:
          # curl -X POST https://<your-astronomer-cluster-url>/deploy_dag -d @dag.py
