name: Deploy Airflow DAG to Astronomer

on:
  # Trigger on push or pull request to the `main` branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Trigger manually using workflow_dispatch
  workflow_dispatch:
    inputs:
      deploymentId:
        description: "Deployment ID"
        required: true
        type: string
      apiToken:
        description: "Astro API Token"
        required: true
        type: string

env:
  ASTRO_API_TOKEN: ${{ inputs.apiToken || secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: ${{ inputs.deploymentId || vars.DEPLOYMENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the Astronomer CLI
      - name: Install Astronomer CLI
        run: |
          sudo curl -sSL https://install.astronomer.io | sudo bash
          export PATH=$PATH:$HOME/.astro/bin

      - name: Authenticate with Astronomer
        run: |
          if [ "${{ secrets.ASTRO_API_TOKEN }}" == "" ]; then
          echo "Error: ASTRO_API_TOKEN is missing. Please set it in GitHub Secrets."
          exit 1
          fi
          astro login --token-login "${{ secrets.ASTRO_API_TOKEN }}" || {
          echo "Authentication failed. Please check your token and permissions."
          exit 1
          }


      # Set Astronomer Workspace
      - name: Set Astronomer Workspace
        run: |
          if [ "${{ env.DEPLOYMENT_ID }}" == "" ]; then
            echo "Missing DEPLOYMENT_ID. Please provide it via workflow inputs or GitHub environment variables."
            exit 1
          fi
          astro context switch ${{ env.DEPLOYMENT_ID }}

      # Deploy the DAG
      - name: Deploy DAG
        run: |
          cd path/to/your-astro-project # Update this to your Astronomer project path
          astro deploy ${{ env.DEPLOYMENT_ID }}
